import { ANTIGRAVITY_PRESETS } from "@/lib/antigravity/presets"
import { ANTIGRAVITY_DEFAULTS } from "@/lib/antigravity/types"
import { ANTIGRAVITY_CONTROLS } from "@/playground/antigravity/schema"
import {
    APERTURE_CONTROLS,
    APERTURE_DEFAULTS,
    APERTURE_PRESETS,
    APERTURE_PRESET_VALUES,
} from "@/playground/aperture/schema"
import { PRISM_CONTROLS, PRISM_DEFAULTS, PRISM_PRESETS } from "@/playground/prism/schema"
import {
    ANAGLYPH_CONTROLS,
    ANAGLYPH_DEFAULTS,
    CHROMA_CONTROLS,
    CHROMA_DEFAULTS,
    CONCERTINA_CONTROLS,
    CONCERTINA_DEFAULTS,
    CONTACT_CONTROLS,
    CONTACT_DEFAULTS,
    DIORAMA_CONTROLS,
    DIORAMA_DEFAULTS,
    DIORAMA_EXAMPLES,
    DIORAMA_PRESET_VALUES,
    EMULSION_CONTROLS,
    EMULSION_DEFAULTS,
    GANTRY_CONTROLS,
    GANTRY_DEFAULTS,
    GANTRY_PRESETS,
    GNOMON_CONTROLS,
    GNOMON_DEFAULTS,
    INK_CONTROLS,
    INK_DEFAULTS,
    LATTICE_CONTROLS,
    LATTICE_DEFAULTS,
    LENTICULAR_CONTROLS,
    LENTICULAR_DEFAULTS,
    MENISCUS_CONTROLS,
    MENISCUS_DEFAULTS,
    NIMBUS_CONTROLS,
    NIMBUS_DEFAULTS,
    NIMBUS_DOC_PRESETS,
    PALIMPSEST_CONTROLS,
    PALIMPSEST_DEFAULTS,
    PEEL_CONTROLS,
    PEEL_DEFAULTS,
    PEEL_PRESETS,
    PHOSPHOR_CONTROLS,
    PHOSPHOR_DEFAULTS,
    QUARTZ_CONTROLS,
    QUARTZ_DEFAULTS,
    QUIVER_CONTROLS,
    QUIVER_DEFAULTS,
    SONAR_CONTROLS,
    SONAR_DEFAULTS,
    TIDE_CONTROLS,
    TIDE_DEFAULTS,
    DRENCH_CONTROLS,
    DRENCH_DEFAULTS,
    ECLIPSE_CONTROLS,
    ECLIPSE_DEFAULTS,
    ELEMENTAL_CONTROLS,
    ELEMENTAL_DEFAULTS,
    FACET_CONTROLS,
    FACET_DEFAULTS,
    GAZE_CONTROLS,
    GAZE_DEFAULTS,
    KERN_CONTROLS,
    KERN_DEFAULTS,
    LOADERS_CONTROLS,
    LOADERS_DEFAULTS,
    LODESTONE_CONTROLS,
    LODESTONE_DEFAULTS,
    LOUVRE_CONTROLS,
    LOUVRE_DEFAULTS,
    MEADOW_CONTROLS,
    MEADOW_DEFAULTS,
    OVERPRINT_CONTROLS,
    OVERPRINT_DEFAULTS,
    PERSEID_CONTROLS,
    PERSEID_DEFAULTS,
    RASTER_CONTROLS,
    RASTER_DEFAULTS,
    RICOCHET_CONTROLS,
    RICOCHET_DEFAULTS,
    TESSERA_CONTROLS,
    TESSERA_DEFAULTS,
    UNDERTOW_CONTROLS,
    UNDERTOW_DEFAULTS,
    WAKE_CONTROLS,
    WAKE_DEFAULTS,
    VELLUM_CONTROLS,
    VELLUM_DEFAULTS,
    WASH_CONTROLS,
    WASH_DEFAULTS,
} from "@/playground/experimental/schemas"
import {
    BITMAP_CONTROLS,
    BITMAP_DEFAULTS,
    BITMAP_PRESETS,
    BITMAP_PRESET_VALUES,
} from "@/playground/bitmap/schema"
import {
    GRID_TRAIL_CONTROLS,
    GRID_TRAIL_DEMO_DEFAULTS,
    GRID_TRAIL_PRESETS,
    GRID_TRAIL_PRESET_VALUES,
} from "@/playground/grid-trail/schema"
import {
    REEL_CONTROLS,
    REEL_DEFAULTS,
    REEL_PRESETS,
    REEL_PRESET_VALUES,
} from "@/playground/reel/schema"
import {
    SCROLL_STACK_CONTROLS,
    SCROLL_STACK_DEFAULTS,
    SCROLL_STACK_PRESETS,
    SCROLL_STACK_PRESET_VALUES,
} from "@/playground/scroll-stack/schema"
import {
    SPLIT_FLAP_CONTROLS,
    SPLIT_FLAP_DEFAULTS,
    SPLIT_FLAP_PRESETS,
    SPLIT_FLAP_PRESET_VALUES,
} from "@/playground/split-flap/schema"
import {
    STENCIL_CONTROLS,
    STENCIL_DEFAULTS,
    STENCIL_PRESETS,
    STENCIL_PRESET_VALUES,
} from "@/playground/stencil/schema"
import {
    TRAILING_CURSOR_CONTROLS,
    TRAILING_CURSOR_DEFAULTS,
    TRAILING_CURSOR_PRESETS,
    TRAILING_CURSOR_PRESET_VALUES,
} from "@/playground/trailing-cursor/schema"
import {
    BEZEL_CONTROLS,
    BEZEL_DEFAULTS,
    BEZEL_PRESETS,
    DITHER_CONTROLS,
    DITHER_DEFAULTS,
    DITHER_PRESETS,
    KEYCAP_CONTROLS,
    KEYCAP_DEFAULTS,
    TAG_CONTROLS,
    TAG_DEFAULTS,
    SEAM_CONTROLS,
    SEAM_DEFAULTS,
    SEAM_PRESETS,
} from "@/playground/interface/schemas"
import type { PanelPreset } from "@/playground/panel/types"

import { DOC_CATEGORIES, type DocCategory, type DocEntry, type DocPreset } from "./types"

/** Bridges the older `PanelPreset[]` + values map onto one preset shape. */
function presetsFrom(
    list: PanelPreset[],
    values: Record<string, Record<string, unknown>>,
): DocPreset[] {
    return list.map((preset) => ({
        id: preset.id,
        label: preset.label,
        hint: preset.hint,
        values: values[preset.id] ?? {},
    }))
}

/** A stronger pull than the component default, so the demo reads at a glance. */
const LODESTONE_DEMO_PULL = { radius: 150, strength: 0.5, maxDisplacement: 30, lift: 0.05 }

export const REPOSITORY_URL = "https://github.com/VladyslavPilkevych/zerogravity-ui"

export const COMPONENTS: DocEntry[] = [
    {
        slug: "antigravity",
        name: "Antigravity",
        label: "Particle field",
        description: "A particle field that flows around the cursor and settles into formations.",
        category: "Backgrounds",
        status: "stable",
        dependencies: [],
        tags: ["particles", "background", "hero", "cursor", "pixel", "canvas", "interactive"],
        defaults: ANTIGRAVITY_DEFAULTS as unknown as Record<string, unknown>,
        controls: ANTIGRAVITY_CONTROLS,
        presets: [...ANTIGRAVITY_PRESETS]
            // the docs open on the strongest demonstration; the exported order stays stable
            .sort((a, b) => Number(b.id === "pixel") - Number(a.id === "pixel"))
            .map((preset) => ({
                id: preset.id,
                label: preset.label,
                hint: preset.hint,
                values: (preset.id === "pixel"
                    ? // the hero grid is sized for a full viewport; fit it to the preview frame
                      {
                          ...preset.options,
                          formation: { ...preset.options.formation, radius: 290 },
                      }
                    : preset.options) as Record<string, unknown>,
            })),
        extraProps: [
            {
                name: "onStats",
                type: "(stats: AntigravityStats) => void",
                default: "—",
                description: "Frame statistics: fps, particles drawn, batches, ms per frame.",
            },
            {
                name: "ref",
                type: "Ref<AntigravityHandle>",
                default: "—",
                description: "Imperative handle exposing burst() and colorBurst().",
            },
        ],
        preview: { minHeight: 520, bleed: true, wide: true },
    },
    {
        slug: "scroll-stack",
        name: "ScrollStack",
        label: "Stacking sections",
        description: "Full-height sections that slide over each other on scroll, and unstack back.",
        category: "Scroll",
        status: "stable",
        dependencies: [],
        tags: ["scroll", "stack", "sticky", "cards", "sections"],
        defaults: SCROLL_STACK_DEFAULTS as unknown as Record<string, unknown>,
        controls: SCROLL_STACK_CONTROLS,
        presets: presetsFrom(
            SCROLL_STACK_PRESETS,
            SCROLL_STACK_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        omit: ["cards", "sizeMix"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "One element per card. Each becomes a sticky section.",
            },
            {
                name: "heights",
                type: "string[]",
                default: "—",
                description: "Per-card height override, in place of the shared height.",
            },
            {
                name: "onActiveChange",
                type: "(index: number) => void",
                default: "—",
                description: "Fires when the front-most card changes.",
            },
        ],
        children: "<article>Card one</article>",
        preview: {
            port: true,
            minHeight: 560,
            wide: true,
            note: "Scaled down to fit the frame: short cards and a small peek, so the whole deck is visible at once. On a page you would use full-height sections and no peek.",
        },
    },
    {
        slug: "aperture",
        name: "Aperture",
        label: "Scroll-framed reveal",
        description: "A full-bleed panel that closes into a framed card as you scroll, or opens.",
        category: "Scroll",
        status: "stable",
        dependencies: [],
        tags: ["scroll", "frame", "clip-path", "reveal", "zoom", "hero"],
        defaults: APERTURE_DEFAULTS as unknown as Record<string, unknown>,
        controls: APERTURE_CONTROLS,
        presets: presetsFrom(
            APERTURE_PRESETS,
            APERTURE_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "The panel content. It never rescales — only the window changes.",
            },
            {
                name: "onProgress",
                type: "(progress: number) => void",
                default: "—",
                description: "Scroll progress from 0 to 1.",
            },
        ],
        children: "<div>Panel content</div>",
        preview: {
            port: true,
            minHeight: 560,
            wide: true,
            note: "Scaled down to fit the frame, and set to open so the panel starts as a card and grows to full bleed. On a page the pane is the viewport and it reads page scroll.",
        },
    },
    {
        slug: "elemental",
        name: "Elemental",
        label: "Electric and fire border",
        description: "An animated edge that wraps any content in electricity or fire.",
        category: "Surfaces",
        status: "stable",
        dependencies: [],
        tags: ["border", "glow", "fire", "electricity", "card", "wrapper", "effect"],
        defaults: ELEMENTAL_DEFAULTS,
        controls: ELEMENTAL_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Whatever the edge wraps. It stays fully interactive.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Freeze the edge in its static state.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description: "Fall back to the static edge when the user asks for less motion.",
            },
        ],
        children: "<Card />",
        preview: { minHeight: 520 },
    },
    {
        slug: "louvre",
        name: "Louvre",
        label: "Rotating blinds reveal",
        description: "Sticky blinds whose slats rotate away to reveal the section behind them.",
        category: "Scroll",
        status: "stable",
        dependencies: [],
        tags: ["scroll", "blinds", "slats", "reveal", "transition"],
        fixedProps: ["front={<Cover />}", "back={<Revealed />}"],
        defaults: LOUVRE_DEFAULTS,
        controls: LOUVRE_CONTROLS,
        extraProps: [
            {
                name: "front",
                type: "ReactNode",
                default: "—",
                description: "What the closed blinds show.",
            },
            {
                name: "back",
                type: "ReactNode",
                default: "—",
                description: "What is revealed once the slats open.",
            },
            {
                name: "scrollContainer",
                type: "RefObject<HTMLElement>",
                default: "—",
                description: "Drive the reveal from a scrollable element instead of the page.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Skip the transition and show the back section.",
            },
        ],
        preview: {
            port: true,
            minHeight: 560,
            wide: true,
            note: "Scaled down to fit the frame, so one full turn of the blinds is visible here. On a page the pane is the viewport and it reads page scroll.",
        },
    },
    {
        slug: "undertow",
        name: "Undertow",
        label: "Liquid image reveal",
        description:
            "Two images and one membrane: the pointer parts the surface and the picture beneath comes through.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["image", "reveal", "before after", "liquid", "pointer", "canvas"],
        defaults: UNDERTOW_DEFAULTS,
        controls: UNDERTOW_CONTROLS,
        extraProps: [
            {
                name: "frontSrc",
                type: "string",
                default: "—",
                description: "The image on top, the one the pointer parts.",
            },
            {
                name: "backSrc",
                type: "string",
                default: "—",
                description: "The image underneath, revealed where the surface is disturbed.",
            },
            {
                name: "alt",
                type: "string",
                default: "—",
                description: "Describes the pair; both images render into one canvas.",
            },
            {
                name: "objectPosition",
                type: "string",
                default: '"50% 50%"',
                description: "Where both images sit when the box crops them.",
            },
            {
                name: "aspect",
                type: "string",
                default: "—",
                description: "Locks the box to a ratio, for example `16 / 10`.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds the still, composed state instead of animating.",
            },
        ],
        preview: {
            minHeight: 460,
            note: "A tap works too, so the reveal is not lost on a touch screen.",
        },
    },
    {
        slug: "wake",
        name: "Wake",
        label: "Water ripple",
        description:
            "Water over a floor: the pointer pushes waves that spread, interfere and bend what lies underneath.",
        category: "Backgrounds",
        status: "stable",
        dependencies: [],
        tags: ["water", "ripple", "liquid", "background", "pointer", "refraction", "canvas"],
        defaults: WAKE_DEFAULTS,
        controls: WAKE_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Content above the water. Stays crisp and interactive.",
            },
            {
                name: "src",
                type: "string",
                default: "—",
                description:
                    "An image to lay under the water, cover-fitted. Falls back to surface.",
            },
            {
                name: "enableOnTouch",
                type: "boolean",
                default: "true",
                description:
                    "Answer a finger: a tap drops a ripple, a sideways drag leaves a wake. Vertical scrolling and pinch-zoom still work.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds one still, refracted frame instead of animating.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description: "Under prefers-reduced-motion, show the still frame.",
            },
        ],
        children: "<Content />",
        preview: { minHeight: 400, bleed: true },
    },
    {
        slug: "drench",
        name: "Drench",
        label: "Rain-revealed text",
        description: "A word that is already there, and rain that finds it.",
        category: "Typography",
        status: "experimental",
        dependencies: [],
        tags: ["text", "rain", "water", "reveal", "weather", "drops", "canvas"],
        defaults: DRENCH_DEFAULTS,
        controls: DRENCH_CONTROLS,
        extraProps: [
            {
                name: "as",
                type: "ElementType",
                default: '"p"',
                description: "The element the real text renders as, e.g. h1 for a hero heading.",
            },
            {
                name: "seed",
                type: "number",
                default: "1",
                description: "Fixes every drop, bead and drip.",
            },
            {
                name: "freezeAt",
                type: "number",
                default: "—",
                description: "Simulate this many frames, draw once and hold (for snapshots).",
            },
            {
                name: "fontFamily / fontWeight",
                type: "string / number",
                default: '"system-ui, sans-serif" / 800',
                description: "Face of the letters; heavy weights hold more water.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds a still, soaked state with no falling rain.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description: "Under prefers-reduced-motion, show the still soaked state.",
            },
        ],
        preview: {
            minHeight: 380,
            bleed: true,
            note: "The text stays real text: the canvas is decoration, and screen readers get the word.",
        },
    },
    {
        slug: "perseid",
        name: "Perseid",
        label: "Meteor shower",
        description: "A meteor shower with bright heads, tapered trails and real depth.",
        category: "Backgrounds",
        status: "experimental",
        dependencies: [],
        tags: ["meteor", "stars", "space", "background", "ambient", "canvas"],
        defaults: PERSEID_DEFAULTS,
        controls: PERSEID_CONTROLS,
        omit: ["paletteName"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Content laid over the sky.",
            },
            {
                name: "colors",
                type: "string[]",
                default: "PERSEID_COLORS",
                description: "The palette meteors are drawn from.",
            },
            {
                name: "seed",
                type: "number",
                default: "—",
                description: "Fixes the sky, so the same seed gives the same meteors every time.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds a still sky instead of animating.",
            },
        ],
        preview: { minHeight: 400, bleed: true },
    },
    {
        slug: "gaze",
        name: "Gaze",
        label: "3D pointer tracking",
        description: "A model whose eyes lead and whose head follows, wherever the pointer goes.",
        category: "Media",
        status: "experimental",
        dependencies: ["three"],
        tags: ["3d", "model", "eyes", "head", "cursor", "look", "follow", "webgl", "gltf"],
        defaults: GAZE_DEFAULTS,
        controls: GAZE_CONTROLS,
        extraProps: [
            {
                name: "src",
                type: "string",
                default: "—",
                description: "A `.glb` or `.gltf` URL. Omit it for the built-in low-poly owl.",
            },
            {
                name: "tracking",
                type: "{ head?, leftEye?, rightEye? }",
                default: "—",
                description: "Node names in your model. Missing ones are skipped.",
            },
            {
                name: "label",
                type: "string",
                default: '"A model that follows the pointer"',
                description: "Describes the model for anything that cannot see it.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds the neutral pose instead of following the pointer.",
            },
        ],
        preview: {
            minHeight: 420,
            note: "The owl is original, built from primitives: no asset to download or credit. Three.js loads only when a Gaze mounts.",
        },
    },
    {
        slug: "eclipse",
        name: "Eclipse",
        label: "Covering sections",
        description: "Each section pins, and the next one slides over it until nothing is left.",
        category: "Scroll",
        status: "stable",
        dependencies: [],
        tags: ["scroll", "sections", "cover", "sticky", "pin", "transition"],
        defaults: ECLIPSE_DEFAULTS,
        controls: ECLIPSE_CONTROLS,
        tag: "Eclipse",
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "One `EclipseSection` per panel. Order is the cover order.",
            },
            {
                name: "height",
                type: "string",
                default: '"100vh"',
                description: "How long each section stays pinned.",
            },
            {
                name: "scrollContainer",
                type: "RefObject<HTMLElement>",
                default: "—",
                description: "Drive it from a scrollable element instead of the page.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Drops the pinning entirely: sections simply follow one another.",
            },
            {
                name: "onActiveChange",
                type: "(index: number) => void",
                default: "—",
                description: "Called when the section in view changes, not on every frame.",
            },
        ],
        children: "<EclipseSection>One</EclipseSection>",
        preview: {
            port: true,
            minHeight: 560,
            wide: true,
            note: "Scaled to the frame so the whole takeover is visible here. On a page each section is a full viewport.",
        },
    },
    {
        slug: "prism",
        name: "Prism",
        label: "Glass refraction",
        description:
            "A slab of glass that takes the pointer as its light source: the content splits into red, green and blue, the edge turns to a rainbow and a spectrum falls behind it.",
        category: "Surfaces",
        status: "experimental",
        dependencies: [],
        tags: [
            "glass",
            "prism",
            "refraction",
            "spectrum",
            "rainbow",
            "3d",
            "tilt",
            "card",
            "wrapper",
        ],
        defaults: PRISM_DEFAULTS,
        controls: PRISM_CONTROLS,
        presets: PRISM_PRESETS,
        // the docs open louder than the library defaults, so the snippet has to say so
        required: ["strength", "tilt", "depth", "dispersion"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Whatever sits inside the glass. Stays interactive.",
            },
            {
                name: "pointer",
                type: "{ x: number; y: number }",
                default: "\u2014",
                description:
                    "Pins the light to a point, 0 to 1 in the slab's own box, instead of following the pointer.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds the light at rest and ignores the pointer.",
            },
        ],
        children: "<Card />",
        preview: {
            minHeight: 480,
            bleed: true,
            note: "Drag on touch screens. Under reduced motion the light rests in the top left corner.",
        },
    },
    {
        slug: "gnomon",
        name: "Gnomon",
        label: "Pointer light and shadows",
        description:
            "The pointer becomes a lamp, and everything inside casts a shadow away from it.",
        category: "Surfaces",
        status: "stable",
        dependencies: [],
        tags: ["shadow", "light", "lamp", "depth", "pointer", "wrapper", "css"],
        defaults: GNOMON_DEFAULTS,
        controls: GNOMON_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Each direct child casts its own shadow.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Pins the light where it started.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description: "Holds the light at rest when the user asks for less motion.",
            },
        ],
        children: "<Card />",
        preview: { minHeight: 380 },
    },
    {
        slug: "lattice",
        name: "Lattice",
        label: "Elastic line mesh",
        description:
            "A line mesh that bulges away from the pointer, and lets go where it stretches.",
        category: "Backgrounds",
        status: "stable",
        dependencies: [],
        tags: ["mesh", "grid", "lines", "background", "pointer", "canvas"],
        defaults: LATTICE_DEFAULTS,
        controls: LATTICE_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Content laid over the mesh.",
            },
            {
                name: "enableOnTouch",
                type: "boolean",
                default: "false",
                description: "Let a coarse pointer push the mesh too.",
            },
        ],
        preview: { minHeight: 420, bleed: true },
    },
    {
        slug: "chroma",
        name: "Chroma",
        label: "Colour cursor trail",
        description:
            "A soft chromatic cursor trail that curves smoothly behind the pointer and fades out.",
        category: "Cursor",
        status: "stable",
        dependencies: [],
        tags: ["cursor", "trail", "pointer", "rainbow", "chromatic", "canvas"],
        defaults: CHROMA_DEFAULTS,
        controls: CHROMA_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "The surface the trail is drawn over.",
            },
            {
                name: "colors",
                type: "[string, string, string]",
                default: "CHROMA_COLORS",
                description:
                    "Fresh, middle and faded tint of the trail. Any CSS colour, including var().",
            },
            {
                name: "enableOnTouch",
                type: "boolean",
                default: "false",
                description:
                    "Let a finger draw the trail too. A sideways drag draws; vertical scrolling still works.",
            },
            {
                name: "paused",
                type: "boolean",
                default: "false",
                description: "Time advances one frame per pointer sample, never on its own.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "No trail at all.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description:
                    "Under prefers-reduced-motion, a still glow under the pointer instead.",
            },
        ],
        preview: {
            minHeight: 400,
            bleed: true,
            note: "A cursor effect: on a touch screen it stays off unless enableOnTouch is set.",
        },
    },
    {
        slug: "sonar",
        name: "Sonar",
        label: "Shockwave dot field",
        description: "A dot field that a shockwave crosses whenever the surface is pressed.",
        category: "Backgrounds",
        status: "stable",
        dependencies: [],
        tags: ["dots", "shockwave", "ripple", "click", "press", "background", "canvas"],
        defaults: SONAR_DEFAULTS,
        controls: SONAR_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Content laid over the field.",
            },
        ],
        preview: { minHeight: 400, bleed: true },
    },
    {
        slug: "concertina",
        name: "Concertina",
        label: "Folding panels",
        tag: "Concertina",
        description:
            "Panels hinged alternately, folding flat as they reach the middle of the view.",
        category: "Scroll",
        status: "experimental",
        dependencies: [],
        tags: ["scroll", "fold", "accordion", "paper", "3d", "sections"],
        defaults: CONCERTINA_DEFAULTS,
        controls: CONCERTINA_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "One `ConcertinaPanel` per leaf.",
            },
            {
                name: "height",
                type: "string",
                default: '"62vh"',
                description: "How tall each leaf is.",
            },
            {
                name: "scrollContainer",
                type: "RefObject<HTMLElement>",
                default: "\u2014",
                description: "Drive it from a scrollable element instead of the page.",
            },
        ],
        children: "<ConcertinaPanel>Fold</ConcertinaPanel>",
        preview: { port: true, minHeight: 520, wide: true },
    },
    {
        slug: "peel",
        name: "Peel",
        label: "Page peel reveal",
        description: "The top sheet lifts off the one underneath as the section scrolls past.",
        category: "Scroll",
        status: "stable",
        dependencies: [],
        tags: ["scroll", "peel", "page", "sheet", "curl", "reveal", "sticky"],
        defaults: PEEL_DEFAULTS,
        controls: PEEL_CONTROLS,
        presets: PEEL_PRESETS,
        // front and back are required JSX, the same whichever corner is picked
        fixedProps: ["front={<Cover />}", "back={<Underneath />}"],
        extraProps: [
            {
                name: "front",
                type: "ReactNode",
                default: "\u2014",
                description: "The sheet on top, the one that lifts away.",
            },
            {
                name: "back",
                type: "ReactNode",
                default: "\u2014",
                description: "What is underneath it.",
            },
            {
                name: "height",
                type: "string",
                default: '"100vh"',
                description: "How tall the pinned stage is.",
            },
            {
                name: "scrollContainer",
                type: "RefObject<HTMLElement>",
                default: "\u2014",
                description: "Drive it from a scrollable element instead of the page.",
            },
            {
                name: "progress",
                type: "number",
                default: "\u2014",
                description: "Set the lift yourself, 0 to 1. Scroll is then ignored.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Drops the peel: both layers stack as ordinary blocks.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description: "Stacks the layers when the user asks for less motion.",
            },
        ],
        preview: { port: true, minHeight: 520, wide: true },
    },
    {
        slug: "gantry",
        name: "Gantry",
        label: "Horizontal scroll rail",
        description: "A rail of cards that travels sideways while the page scrolls down.",
        category: "Scroll",
        status: "stable",
        dependencies: [],
        tags: ["scroll", "horizontal", "rail", "carousel", "gallery", "sticky", "pixel"],
        defaults: GANTRY_DEFAULTS,
        controls: GANTRY_CONTROLS,
        presets: GANTRY_PRESETS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "One card per stop along the rail.",
            },
            {
                name: "height",
                type: "string",
                default: '"80vh"',
                description: "How tall the pinned stage is.",
            },
            {
                name: "label",
                type: "string",
                default: '"Horizontal gallery"',
                description: "Names the rail once reduced motion turns it into a scroller.",
            },
            {
                name: "onProgress",
                type: "(progress: number) => void",
                default: "\u2014",
                description: "Called with 0 to 1 as the rail travels.",
            },
            {
                name: "progress",
                type: "number",
                default: "\u2014",
                description: "Set the rail position yourself, 0 to 1. Scroll is then ignored.",
            },
        ],
        children: "<Card />",
        preview: { port: true, minHeight: 520, wide: true },
    },
    {
        slug: "tide",
        name: "Tide",
        label: "Wavy edge",
        description: "A wavy, slowly drifting contour for any card, section or image.",
        category: "Surfaces",
        status: "stable",
        dependencies: [],
        tags: ["wave", "contour", "edge", "clip-path", "liquid", "card", "image", "wrapper"],
        defaults: TIDE_DEFAULTS,
        controls: TIDE_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Whatever gets the contour. It stays fully interactive.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Hold a static wavy contour.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description: "Hold the static contour when the user asks for less motion.",
            },
        ],
        children: "<Card />",
        preview: { minHeight: 420 },
    },
    {
        slug: "palimpsest",
        name: "Palimpsest",
        label: "Layered draft text",
        description: "A word that comes apart into the drafts written underneath it.",
        category: "Typography",
        status: "stable",
        dependencies: [],
        tags: ["text", "type", "layers", "ghost", "hover", "heading"],
        required: ["text"],
        defaults: PALIMPSEST_DEFAULTS,
        controls: PALIMPSEST_CONTROLS,
        extraProps: [
            {
                name: "as",
                type: '"span" | "h1" | "h2" | "h3" | "p"',
                default: '"span"',
                description: "The tag the real text is rendered as.",
            },
            {
                name: "colors",
                type: "string[]",
                default: "PALIMPSEST_COLORS",
                description: "The tints the ghost layers are drawn in.",
            },
        ],
        preview: { minHeight: 320 },
    },
    {
        slug: "quiver",
        name: "Quiver",
        label: "Letter wave",
        description: "A crest that travels along a line of type, lifting letters as it passes.",
        category: "Typography",
        status: "experimental",
        dependencies: [],
        tags: ["text", "type", "wave", "letters", "pointer", "css"],
        defaults: QUIVER_DEFAULTS,
        controls: QUIVER_CONTROLS,
        extraProps: [
            {
                name: "as",
                type: '"span" | "h1" | "h2" | "h3" | "p"',
                default: '"span"',
                description: "The tag the text is rendered as.",
            },
        ],
        preview: { minHeight: 300 },
    },
    {
        slug: "ink",
        name: "Ink",
        label: "Ink bleed text",
        description:
            "A word that soaks into the paper: ink wicks out along the fibres, feathers, and dries to a darker tide line.",
        category: "Typography",
        status: "experimental",
        dependencies: [],
        tags: ["text", "type", "ink", "bleed", "paper", "diffusion", "canvas"],
        defaults: INK_DEFAULTS,
        controls: INK_CONTROLS,
        extraProps: [
            {
                name: "time",
                type: "number",
                default: "—",
                description: "Hold the soak this many seconds in, for stills and snapshots.",
            },
            {
                name: "fontFamily / fontWeight",
                type: "string / number",
                default: "Georgia, 700",
                description: "The face the word is set in before it is pressed into the paper.",
            },
        ],
        preview: {
            minHeight: 360,
            bleed: true,
            note: "Drag on the paper to write. The word stays real text; the canvas is only how it is drawn.",
        },
    },
    {
        slug: "phosphor",
        name: "Phosphor",
        label: "CRT text",
        description: "Type burned into a tube: scanlines, bloom and three guns that disagree.",
        category: "Typography",
        status: "stable",
        dependencies: [],
        tags: ["text", "type", "crt", "retro", "scanlines", "glow", "terminal"],
        required: ["text"],
        defaults: PHOSPHOR_DEFAULTS,
        controls: PHOSPHOR_CONTROLS,
        extraProps: [
            {
                name: "as",
                type: '"span" | "h1" | "h2" | "h3" | "p"',
                default: '"span"',
                description: "The tag the text is rendered as.",
            },
        ],
        preview: { minHeight: 300, bleed: true },
    },
    {
        slug: "lenticular",
        name: "Lenticular",
        label: "Two-image lens flip",
        description: "Two pictures interlaced under one lens, swapping as you move across it.",
        category: "Media",
        status: "stable",
        dependencies: [],
        tags: ["image", "before after", "compare", "lens", "hologram", "pointer"],
        fixedProps: [
            'frontSrc="/day.jpg"',
            'backSrc="/night.jpg"',
            'alt="The same street by day and by night"',
        ],
        defaults: LENTICULAR_DEFAULTS,
        controls: LENTICULAR_CONTROLS,
        extraProps: [
            {
                name: "frontSrc",
                type: "string",
                default: "\u2014",
                description: "The image seen from the left.",
            },
            {
                name: "backSrc",
                type: "string",
                default: "\u2014",
                description: "The image seen from the right.",
            },
            {
                name: "alt",
                type: "string",
                default: "\u2014",
                description: "Describes the pair; one card, one description.",
            },
            {
                name: "position",
                type: "number",
                default: "\u2014",
                description: "Holds the print at a position, 0 to 1, and ignores the pointer.",
            },
            {
                name: "aspect",
                type: "string",
                default: '"4 / 3"',
                description: "Locks the card to a ratio.",
            },
            {
                name: "objectPosition",
                type: "string",
                default: '"50% 50%"',
                description: "Where both pictures sit when cropped.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds the print head-on, both pictures interlaced.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description:
                    "Under prefers-reduced-motion, no tilt or easing: the swap follows the pointer directly.",
            },
        ],
        preview: {
            minHeight: 460,
            note: "On a touch screen a tap or a sideways drag scrubs the print; vertical scrolling still works.",
        },
    },
    {
        slug: "anaglyph",
        name: "Anaglyph",
        label: "3D anaglyph image",
        description: "A picture split into two eyes that converge wherever the pointer rests.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["image", "3d", "red cyan", "stereo", "chromatic", "depth"],
        defaults: ANAGLYPH_DEFAULTS,
        controls: ANAGLYPH_CONTROLS,
        extraProps: [
            {
                name: "src",
                type: "string",
                default: "\u2014",
                description: "Any image URL or local asset.",
            },
            {
                name: "alt",
                type: "string",
                default: "\u2014",
                description: "Describes the picture once, on the plate underneath.",
            },
        ],
        preview: { minHeight: 460 },
    },
    {
        slug: "contact",
        name: "Contact",
        label: "Scrubbable contact sheet",
        description: "A contact sheet you scrub through with the pointer or the arrow keys.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["image", "sequence", "scrub", "film", "gallery", "slider"],
        defaults: CONTACT_DEFAULTS,
        controls: CONTACT_CONTROLS,
        extraProps: [
            {
                name: "frames",
                type: "string[]",
                default: "\u2014",
                description: "The sequence, in order.",
            },
            {
                name: "labels",
                type: "string[]",
                default: "\u2014",
                description: "A label per frame, read out by the slider.",
            },
            {
                name: "onFrameChange",
                type: "(index: number) => void",
                default: "\u2014",
                description: "Called when the frame changes, not on every move.",
            },
        ],
        preview: { minHeight: 480 },
    },
    {
        slug: "emulsion",
        name: "Emulsion",
        label: "Film photo filter",
        description: "A photographic treatment: halation, grain, a light leak and lifted shadows.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["image", "film", "photo", "filter", "halation", "grain", "vintage"],
        defaults: EMULSION_DEFAULTS,
        controls: EMULSION_CONTROLS,
        extraProps: [
            {
                name: "src",
                type: "string",
                default: "\u2014",
                description: "Any image URL or local asset.",
            },
            {
                name: "alt",
                type: "string",
                default: "\u2014",
                description: "Empty string if the image is decorative.",
            },
            {
                name: "aspect",
                type: "string",
                default: '"3 / 2"',
                description: "Locks the frame to a ratio.",
            },
        ],
        preview: { minHeight: 460 },
    },
    {
        slug: "quartz",
        name: "Quartz",
        label: "Film grain overlay",
        description: "Film grain over anything, from one tile painted once and repeated by CSS.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["grain", "noise", "texture", "overlay", "film", "wrapper"],
        defaults: QUARTZ_DEFAULTS,
        controls: QUARTZ_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Whatever the grain sits over.",
            },
        ],
        children: "<Hero />",
        preview: { minHeight: 380, bleed: true },
    },
    {
        slug: "nimbus",
        name: "Nimbus",
        label: "Ambient scene",
        description:
            "A living section background: layered fog at depth, a slow camera, dust, light sweeps and crossfading colour moods.",
        category: "Backgrounds",
        status: "experimental",
        dependencies: [],
        tags: [
            "fog",
            "clouds",
            "ambient",
            "background",
            "gradient",
            "parallax",
            "loading screen",
            "canvas",
            "cinematic",
            "ken burns",
        ],
        defaults: NIMBUS_DEFAULTS,
        controls: NIMBUS_CONTROLS,
        presets: NIMBUS_DOC_PRESETS,
        omit: ["paletteName"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Content laid over the fog, kept above every layer.",
            },
            {
                name: "colors",
                type: "string[]",
                default: "from the preset",
                description: "One fog palette, replacing the preset's moods.",
            },
            {
                name: "scenes",
                type: "NimbusScene[]",
                default: "from the preset",
                description:
                    "Colour moods ({ fog, sky?, light? }) that crossfade slowly; wins over colors.",
            },
            {
                name: "time",
                type: "number",
                default: "\u2014",
                description: "Hold the field this many seconds in, for stills and screenshots.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Paint one frame and hold it.",
            },
        ],
        children: "<Hero />",
        preview: { minHeight: 420, bleed: true },
    },
    {
        slug: "meniscus",
        name: "Meniscus",
        label: "Liquid progress",
        description: "A vessel that fills with liquid, and keeps sloshing while it waits.",
        category: "Loading & transitions",
        status: "experimental",
        dependencies: [],
        tags: ["loading", "progress", "liquid", "fill", "svg"],
        defaults: MENISCUS_DEFAULTS,
        controls: MENISCUS_CONTROLS,
        extraProps: [
            {
                name: "label",
                type: "string",
                default: '"Loading"',
                description: "What the progress bar announces.",
            },
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Replaces the number inside the vessel.",
            },
        ],
        preview: { minHeight: 340 },
    },
    {
        slug: "reel",
        name: "Reel",
        label: "Carousel",
        description: "A roulette-style carousel you can drag, flick, scroll sideways or step.",
        category: "Media",
        status: "stable",
        dependencies: [],
        tags: ["carousel", "slider", "gallery", "cards", "coverflow", "drag", "swipe"],
        defaults: REEL_DEFAULTS as unknown as Record<string, unknown>,
        controls: REEL_CONTROLS,
        presets: presetsFrom(
            REEL_PRESETS,
            REEL_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        omit: ["items"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "One element per slide.",
            },
            {
                name: "index",
                type: "number",
                default: "—",
                description: "Controlled index of the centred slide.",
            },
            {
                name: "onIndexChange",
                type: "(index: number) => void",
                default: "—",
                description: "Fires when a different slide reaches the centre.",
            },
            {
                name: "label",
                type: "string",
                default: '"Carousel"',
                description: "Accessible name for the carousel region.",
            },
        ],
        children: "<article>Slide one</article>",
        preview: { minHeight: 520, wide: true },
    },
    {
        slug: "raster",
        name: "Raster",
        label: "Stylised image filter",
        description: "One picture through four stylised abstractions: blur, glass, glyph, pixel.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["image", "filter", "pixelate", "ascii", "glass", "blur", "canvas"],
        defaults: RASTER_DEFAULTS,
        controls: RASTER_CONTROLS,
        extraProps: [
            {
                name: "src",
                type: "string",
                default: "—",
                description: "Image URL or imported asset.",
            },
            {
                name: "alt",
                type: "string",
                default: "—",
                description: "Alternative text. Empty string if the image is decorative.",
            },
            {
                name: "aspectRatio",
                type: "string",
                default: '"16 / 9"',
                description: "CSS aspect ratio for the frame.",
            },
        ],
        preview: { minHeight: 460 },
    },
    {
        slug: "stencil",
        name: "Stencil",
        label: "Pattern-filled text",
        description: "Display type filled with stripes, checks, gradients, an image or video.",
        category: "Typography",
        status: "stable",
        required: ["text"],
        dependencies: [],
        tags: ["text", "type", "mask", "pattern", "image", "video", "heading"],
        defaults: STENCIL_DEFAULTS as unknown as Record<string, unknown>,
        controls: STENCIL_CONTROLS,
        presets: presetsFrom(
            STENCIL_PRESETS,
            STENCIL_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        extraProps: [
            {
                name: "media",
                type: "string",
                default: "—",
                description: "Video URL used by the reveal hover mode.",
            },
        ],
        preview: { minHeight: 380 },
    },
    {
        slug: "split-flap",
        name: "SplitFlap",
        label: "Flip board text",
        description:
            "An airport board that flips one character at a time: text, clock or countdown.",
        category: "Typography",
        status: "stable",
        dependencies: [],
        tags: ["text", "flip", "board", "airport", "clock", "countdown", "timer"],
        defaults: SPLIT_FLAP_DEFAULTS as unknown as Record<string, unknown>,
        controls: SPLIT_FLAP_CONTROLS,
        presets: presetsFrom(
            SPLIT_FLAP_PRESETS,
            SPLIT_FLAP_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        extraProps: [
            {
                name: "target",
                type: "Date | number",
                default: "—",
                description: "Deadline for countdown mode.",
            },
        ],
        preview: { minHeight: 340 },
    },
    {
        slug: "kern",
        name: "Kern",
        label: "Variable font hover",
        description: "Glyphs that open up, lift and gain weight as the pointer passes them.",
        category: "Typography",
        status: "stable",
        required: ["text"],
        dependencies: [],
        tags: ["text", "type", "variable font", "hover", "pointer", "weight"],
        defaults: KERN_DEFAULTS,
        controls: KERN_CONTROLS,
        preview: { minHeight: 340 },
    },
    {
        slug: "overprint",
        name: "Overprint",
        label: "Misregistered print text",
        description:
            "Colour separations that misregister on scroll and converge back into register.",
        category: "Typography",
        status: "stable",
        required: ["text"],
        dependencies: [],
        tags: ["text", "type", "cmyk", "print", "risograph", "scroll"],
        defaults: OVERPRINT_DEFAULTS,
        controls: OVERPRINT_CONTROLS,
        preview: {
            minHeight: 340,
            note: "Scrolling the page shifts the plates apart; they converge again when it stops.",
        },
    },
    {
        slug: "bitmap",
        name: "Bitmap",
        label: "Pixel text",
        description:
            "Pixel text set on a 5x7 grid, lit by a sweep, a wave or a cycling palette in pure CSS.",
        category: "Typography",
        status: "stable",
        required: ["text"],
        dependencies: [],
        tags: ["text", "pixel", "8-bit", "retro", "wordmark", "logo", "svg"],
        defaults: BITMAP_DEFAULTS as unknown as Record<string, unknown>,
        controls: BITMAP_CONTROLS,
        presets: presetsFrom(
            BITMAP_PRESETS,
            BITMAP_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        extraProps: [
            {
                name: "color",
                type: "string",
                default: '"currentColor"',
                description: "Single colour used when colors is empty.",
            },
            {
                name: "as",
                type: '"span" | "div" | "p" | "strong" | "h1" … "h6"',
                default: '"span"',
                description: "Element that carries the real, screen-reader text.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description: "Render the static palette when the reader prefers reduced motion.",
            },
        ],
        preview: { minHeight: 340 },
    },
    {
        slug: "grid-trail",
        name: "GridTrail",
        label: "Grid cell trail",
        description: "A pointer trail that lights cells on an invisible grid, then stops the loop.",
        category: "Cursor",
        status: "stable",
        dependencies: [],
        tags: ["cursor", "trail", "grid", "cells", "pixel", "background"],
        defaults: GRID_TRAIL_DEMO_DEFAULTS as unknown as Record<string, unknown>,
        controls: GRID_TRAIL_CONTROLS,
        presets: presetsFrom(
            GRID_TRAIL_PRESETS,
            GRID_TRAIL_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        omit: ["scoped"],
        extraProps: [
            {
                name: "container",
                type: "RefObject<HTMLElement>",
                default: "—",
                description: "Scope the trail to one element instead of the viewport.",
            },
            {
                name: "zIndex",
                type: "number",
                default: "0",
                description: "Stacking level of the trail canvas.",
            },
        ],
        preview: { minHeight: 420, bleed: true, containFixed: true },
    },
    {
        slug: "trailing-cursor",
        name: "TrailingCursor",
        label: "Custom cursor ring",
        description: "A dot pinned to the pointer and a ring that lags, grows and recolours.",
        category: "Cursor",
        status: "stable",
        dependencies: [],
        tags: ["cursor", "pointer", "ring", "dot", "follow", "hover"],
        defaults: TRAILING_CURSOR_DEFAULTS as unknown as Record<string, unknown>,
        controls: TRAILING_CURSOR_CONTROLS,
        presets: presetsFrom(
            TRAILING_CURSOR_PRESETS,
            TRAILING_CURSOR_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        preview: { minHeight: 460, bleed: true, containFixed: true },
    },
    {
        slug: "lodestone",
        name: "Lodestone",
        label: "Magnetic buttons",
        description: "Magnetic buttons that lean toward the pointer but never overlap each other.",
        category: "Cursor",
        status: "stable",
        dependencies: [],
        tags: ["magnetic", "magnet", "button", "cursor", "hover", "cta"],
        defaults: { ...LODESTONE_DEFAULTS, variant: "soft" },
        controls: [
            {
                id: "look",
                title: "Look",
                hint: "the button face",
                open: true,
                controls: [
                    {
                        kind: "select",
                        path: "variant",
                        label: "Variant",
                        options: ["soft", "pixel"],
                    },
                ],
            },
            ...LODESTONE_CONTROLS,
        ],
        presets: [
            {
                id: "pixel",
                label: "Pixel",
                hint: "Stepped corners, a 2px ring and a hard shadow the face presses into",
                values: { variant: "pixel", ...LODESTONE_DEMO_PULL },
            },
            {
                id: "soft",
                label: "Soft",
                hint: "The original translucent pill",
                values: { ...LODESTONE_DEMO_PULL },
            },
        ],
        omit: ["buttons", "spacing"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Button label.",
            },
        ],
        children: "Get started",
        preview: { minHeight: 340 },
    },
    {
        slug: "vellum",
        name: "Vellum",
        label: "Flexible tilt card",
        description:
            "A flexible sheet that leans toward the pointer and dents where it rests, lit smooth or in stepped square cells.",
        category: "Surfaces",
        status: "stable",
        dependencies: [],
        tags: ["tilt", "card", "3d", "hover", "dent", "sheet", "pixel"],
        defaults: VELLUM_DEFAULTS,
        controls: VELLUM_CONTROLS,
        presets: [
            {
                id: "pixel",
                label: "Pixel",
                hint: "The dent drawn in stepped square cells that pinch toward the pointer",
                values: { surface: "pixel", radius: 6 },
            },
            {
                id: "smooth",
                label: "Smooth",
                hint: "The original gradient dent and sheen",
                values: {},
            },
        ],
        omit: ["highlight", "dent", "sheen", "sheenColor"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Whatever sits on the sheet.",
            },
            {
                name: "highlight",
                type: "VellumHighlight | false",
                default: "true",
                description:
                    "Dent and sheen settings, or false to remove the highlight (both surfaces) entirely.",
            },
            {
                name: "pointer",
                type: "{ x: number; y: number }",
                default: "—",
                description:
                    "Presses the sheet at a fixed point, 0 to 1 in its own box, instead of following the pointer.",
            },
        ],
        children: "<div>Card</div>",
        preview: { minHeight: 400 },
    },
    {
        slug: "diorama",
        name: "Diorama",
        label: "Layered parallax",
        description:
            "Near and far layers that move at different speeds, so a flat composition gains real depth.",
        category: "Surfaces",
        status: "stable",
        dependencies: [],
        tags: ["parallax", "depth", "layers", "3d", "pointer", "hero"],
        defaults: DIORAMA_DEFAULTS,
        controls: DIORAMA_CONTROLS,
        presets: presetsFrom(DIORAMA_EXAMPLES, DIORAMA_PRESET_VALUES),
        omit: ["example"],
        exampleProps: {
            key: "example",
            props: {
                product: [
                    "background={<ProductCard />}",
                    "planes={[",
                    "    { content: <SpecLabels />, depth: 0.5 },",
                    "    { content: <SoftShapes />, depth: 1 },",
                    "]}",
                ],
                editorial: [
                    "background={<ArticleWithPicture />}",
                    "planes={[",
                    "    { content: <PictureCaption />, depth: 0.4 },",
                    "    { content: <SoftShapes />, depth: 1 },",
                    "]}",
                ],
                poster: [
                    "background={<SkyAndTitle />}",
                    "planes={[",
                    "    { content: <FarRidge />, depth: 0.45 },",
                    "    { content: <NearHills />, depth: 1 },",
                    "]}",
                ],
                frame: [
                    "background={<CentralMessage />}",
                    "planes={[",
                    "    { content: <SideFoliage />, depth: 0.55 },",
                    "    { content: <CornerFoliage />, depth: 1 },",
                    "]}",
                ],
            },
        },
        extraProps: [
            {
                name: "background",
                type: "ReactNode",
                default: "—",
                description: "The deepest layer, never blurred.",
            },
            {
                name: "planes",
                type: "DioramaPlane[]",
                default: "[]",
                description:
                    "Layers in front of the background, ordered far to near: { content, depth 0–1, blur?, opacity? }.",
            },
        ],
        preview: {
            minHeight: 420,
            note: "Use it when a hero, product shot or poster needs depth: the background stays sharp, nearer planes move further and blur more.",
        },
    },
    {
        slug: "facet",
        name: "Facet",
        label: "Faceted colour surface",
        description:
            "A faceted surface whose colour migrates across the slats instead of switching.",
        category: "Surfaces",
        status: "experimental",
        dependencies: [],
        tags: ["facets", "slats", "gradient", "colour", "background", "hero"],
        defaults: FACET_DEFAULTS,
        controls: FACET_CONTROLS,
        omit: ["paletteName"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Content laid over the surface.",
            },
            {
                name: "palette",
                type: "string[]",
                default: "—",
                description: "Colours the ambient flow moves between.",
            },
        ],
        children: "<div>Hero copy</div>",
        preview: { minHeight: 460, bleed: true },
    },
    {
        slug: "wash",
        name: "Wash",
        label: "Click colour bloom",
        description: "A new colour that spreads outward from wherever the surface was touched.",
        category: "Surfaces",
        status: "stable",
        dependencies: [],
        tags: ["click", "tap", "colour", "bloom", "ripple", "burst", "pixel", "background"],
        defaults: WASH_DEFAULTS,
        controls: WASH_CONTROLS,
        omit: ["paletteName"],
        exampleProps: {
            key: "paletteName",
            props: {
                clay: ['colors={["#4a3328", "#5a4030", "#3d2b2b", "#63483a"]}'],
                tide: ['colors={["#123040", "#17414a", "#0f3a3a", "#1b4c56"]}'],
            },
        },
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Content laid over the wash. Stays interactive.",
            },
            {
                name: "colors",
                type: "string[]",
                default: "five muted tones",
                description:
                    "The cycle of colours to bloom through. Any CSS colour, including var().",
            },
            {
                name: "easing",
                type: "string",
                default: '"cubic-bezier(0.22, 1, 0.36, 1)"',
                description: "Timing function for the spread.",
            },
            {
                name: "seed",
                type: "number",
                default: "1",
                description: "Fixes the fragment pattern of the pixel burst.",
            },
            {
                name: "freezeAt",
                type: "number",
                default: "—",
                description:
                    "Holds the pour and burst at a 0 to 1 progress, for stories and screenshots.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds the current colour and pours nothing.",
            },
        ],
        children: "<div>Hero copy</div>",
        preview: { minHeight: 460, bleed: true },
    },
    {
        slug: "meadow",
        name: "Meadow",
        label: "Animated hero scene",
        description:
            "A living pastel hero scene that drifts, bobs and flutters around your content.",
        category: "Backgrounds",
        status: "stable",
        dependencies: [],
        tags: ["hero", "illustration", "scene", "nature", "playful", "svg", "background"],
        defaults: MEADOW_DEFAULTS,
        controls: MEADOW_CONTROLS,
        omit: [
            "sun",
            "clouds",
            "hills",
            "flowers",
            "balloon",
            "butterflies",
            "birds",
            "mascots",
            "stars",
            "comets",
            "planets",
            "rockets",
            "ufos",
        ],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Content centred inside the scene.",
            },
            {
                name: "scene",
                type: "MeadowScene",
                default: "{}",
                description: "Per-element switches, for example { birds: false, flowers: false }.",
            },
        ],
        children: "<div>Hero copy</div>",
        preview: { minHeight: 520, bleed: true, wide: true },
    },
    {
        slug: "tessera",
        name: "Tessera",
        label: "Route transition",
        description:
            "A tiled route transition: tiles cover the viewport, the route swaps, they retreat.",
        category: "Loading & transitions",
        status: "stable",
        tag: "TesseraProvider",
        dependencies: [],
        tags: ["route", "transition", "page", "tiles", "navigation", "router", "pixel"],
        defaults: TESSERA_DEFAULTS,
        controls: TESSERA_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Your app. Navigation runs through useTessera().",
            },
        ],
        children: "<App />",
        preview: {
            minHeight: 440,
            bleed: true,
            containFixed: true,
            note: "The overlay is position: fixed in real use. It is held inside this frame so the docs stay usable.",
        },
    },
    {
        slug: "ricochet",
        name: "Ricochet",
        label: "Breakable pixel text game",
        description:
            "Short text built from destructible pixel blocks, with breakout or shooter play.",
        category: "Typography",
        status: "stable",
        dependencies: [],
        tags: ["game", "404", "pixel", "arcade", "breakout", "text", "canvas"],
        defaults: RICOCHET_DEFAULTS,
        controls: RICOCHET_CONTROLS,
        extraProps: [
            {
                name: "onClear",
                type: "() => void",
                default: "—",
                description: "Fires once, when the last block is destroyed.",
            },
            {
                name: "interactive",
                type: "boolean",
                default: "true",
                description: "Pointer, keyboard and focus handling.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description: "Render the text standing still when the user asks for less motion.",
            },
        ],
        preview: { minHeight: 480 },
    },
    {
        slug: "dither",
        name: "Dither",
        label: "Pixel hover highlight",
        description:
            "A pixel hover layer for any card, link or button: blocks sweep in from the pointer, or a quick block frame lights the edge.",
        category: "Interface",
        status: "stable",
        dependencies: [],
        tags: ["hover", "focus", "pixel", "card", "link", "button", "navigation", "dither"],
        defaults: DITHER_DEFAULTS,
        controls: DITHER_CONTROLS,
        presets: DITHER_PRESETS,
        children: "<YourCard />",
        extraProps: [
            {
                name: "as",
                type: "ElementType",
                default: '"div"',
                description:
                    'Element or component to render, such as "a", "button" or a router Link.',
            },
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Content drawn above the pixel layer and left fully interactive.",
            },
            {
                name: "colors",
                type: "string[]",
                default: "—",
                description: "Several block colours, assigned per cell. Overrides color.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Render the element without the pixel layer.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description: "Show the settled state instantly instead of sweeping or stepping in.",
            },
        ],
        preview: {
            minHeight: 340,
            note: "The cards are a radio choice and never navigate. Pass as={Link} when a card should.",
        },
    },
    {
        slug: "keycap",
        name: "Keycap",
        label: "Pixel button",
        description:
            "A native button with notched pixel corners, a hard cast shadow it presses into, and a block sweep on hover.",
        category: "Interface",
        status: "stable",
        dependencies: [],
        tags: ["button", "pixel", "press", "cta", "form", "keyboard"],
        defaults: KEYCAP_DEFAULTS,
        controls: KEYCAP_CONTROLS,
        children: "Deploy",
        extraProps: [
            {
                name: "variant",
                type: '"solid" | "outline" | "ghost"',
                default: '"solid"',
                description: "Filled cap, accent outline, or no frame until hovered.",
            },
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Button label. Every native button attribute is passed through.",
            },
            {
                name: "type",
                type: '"button" | "submit" | "reset"',
                default: '"button"',
                description:
                    "Defaults to button, so a Keycap inside a form never submits by accident.",
            },
        ],
        preview: { minHeight: 260 },
    },
    {
        slug: "bezel",
        name: "Bezel",
        label: "Pixel frame",
        description:
            "A frame for any content with stepped corners, a mono label tab and corner ticks that lock on when hovered.",
        category: "Interface",
        status: "stable",
        dependencies: [],
        tags: ["frame", "panel", "card", "border", "pixel", "label"],
        defaults: BEZEL_DEFAULTS,
        controls: BEZEL_CONTROLS,
        presets: BEZEL_PRESETS,
        children: "<YourContent />",
        extraProps: [
            {
                name: "as",
                type: '"div" | "section" | "article" | "aside" | "figure" | "nav" | "li"',
                default: '"div"',
                description: "The element to render.",
            },
            {
                name: "padding",
                type: "number | string",
                default: "20",
                description: "Inner padding; numbers are pixels.",
            },
        ],
        preview: { minHeight: 360 },
    },
    {
        slug: "seam",
        name: "Seam",
        label: "Pixel divider",
        description:
            "A section divider built from pixel blocks: dashes, stairs, a dithered fade or a travelling pulse.",
        category: "Interface",
        status: "stable",
        dependencies: [],
        tags: ["divider", "separator", "hr", "line", "pixel", "section"],
        defaults: SEAM_DEFAULTS,
        controls: SEAM_CONTROLS,
        presets: SEAM_PRESETS,
        extraProps: [
            {
                name: "pattern",
                type: '"dash" | "stair" | "dither" | "pulse"',
                default: '"dash"',
                description: "Block pattern. Pulse animates unless animated is set to false.",
            },
            {
                name: "label",
                type: "ReactNode",
                default: "—",
                description: "Centred mono caption; a string also names the separator.",
            },
            {
                name: "decorative",
                type: "boolean",
                default: "false",
                description: "Hide from assistive technology instead of exposing a separator.",
            },
        ],
        preview: { minHeight: 320 },
    },
    {
        slug: "tag",
        name: "Tag",
        label: "Status tag",
        description:
            "A square status tag whose indicator is a pixel glyph, so the state never relies on colour alone.",
        category: "Interface",
        status: "stable",
        dependencies: [],
        tags: ["tag", "badge", "status", "label", "chip", "pill", "live", "pixel"],
        defaults: TAG_DEFAULTS,
        controls: TAG_CONTROLS,
        children: "Release",
        extraProps: [
            {
                name: "tone",
                type: "string",
                default: "—",
                description: "Override the status colour.",
            },
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "The tag text, rendered as real text.",
            },
        ],
        preview: { minHeight: 220 },
    },
    {
        slug: "loaders",
        name: "Pixel loaders",
        label: "Pixel loaders",
        description:
            "Four retro-digital loading states: a heart, blocks, a bar and a full-screen pulse.",
        category: "Loading & transitions",
        status: "experimental",
        tag: "PixelHeart",
        dependencies: [],
        tags: ["loading", "loader", "spinner", "progress", "skeleton", "pixel"],
        defaults: LOADERS_DEFAULTS,
        controls: LOADERS_CONTROLS,
        omit: ["heartVariant", "blocksVariant", "determinate", "value"],
        extraProps: [
            {
                name: "variant",
                type: '"pulse" | "blink"',
                default: '"pulse"',
                description: "PixelHeart animation style.",
            },
            {
                name: "value",
                type: "number",
                default: "—",
                description: "PixelBar progress from 0 to 1. Omit for an indeterminate bar.",
            },
            {
                name: "label",
                type: "string",
                default: '"Loading"',
                description: "Announced by screen readers while the loader is visible.",
            },
        ],
        preview: { scroll: true, minHeight: 520, wide: true },
    },
]

export const COMPONENT_COUNT = COMPONENTS.length

/** The light list the sidebar needs, so schemas stay out of the client bundle. */
export function sidebarIndex() {
    return COMPONENTS.map((entry) => ({
        slug: entry.slug,
        name: entry.name,
        label: entry.label,
        description: entry.description,
        category: entry.category,
        status: entry.status,
        tags: entry.tags,
    }))
}

export function findComponent(slug: string): DocEntry | undefined {
    return COMPONENTS.find((entry) => entry.slug === slug)
}

/** A URL fragment for a category, since some names carry spaces and "&". */
export function categoryId(category: DocCategory): string {
    return category
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")
}

/**
 * Groups in sidebar order, components alphabetical within each group. Search
 * results pass `ranked` instead, so the best match leads and its group with it.
 */
export function groupByCategory(
    entries: DocEntry[],
    { ranked = false }: { ranked?: boolean } = {},
): { category: DocCategory; items: DocEntry[] }[] {
    if (ranked) {
        const groups: { category: DocCategory; items: DocEntry[] }[] = []
        for (const entry of entries) {
            const found = groups.find((group) => group.category === entry.category)
            if (found) found.items.push(entry)
            else groups.push({ category: entry.category, items: [entry] })
        }
        return groups
    }

    return DOC_CATEGORIES.map((category) => ({
        category,
        items: entries
            .filter((entry) => entry.category === category)
            .sort((a, b) => a.name.localeCompare(b.name)),
    })).filter((group) => group.items.length > 0)
}
