import { ANTIGRAVITY_PRESETS } from "@/lib/antigravity/presets"
import { ANTIGRAVITY_DEFAULTS } from "@/lib/antigravity/types"
import { ANTIGRAVITY_CONTROLS } from "@/playground/antigravity/schema"
import {
    APERTURE_CONTROLS,
    APERTURE_DEFAULTS,
    APERTURE_PRESETS,
    APERTURE_PRESET_VALUES,
} from "@/playground/aperture/schema"
import {
    ANAGLYPH_CONTROLS,
    ANAGLYPH_DEFAULTS,
    CHROMA_CONTROLS,
    CHROMA_DEFAULTS,
    CONCERTINA_CONTROLS,
    CONCERTINA_DEFAULTS,
    CONTACT_CONTROLS,
    CONTACT_DEFAULTS,
    DIORAMA_CONTROLS,
    DIORAMA_DEFAULTS,
    EMULSION_CONTROLS,
    EMULSION_DEFAULTS,
    GANTRY_CONTROLS,
    GANTRY_DEFAULTS,
    GNOMON_CONTROLS,
    GNOMON_DEFAULTS,
    INK_CONTROLS,
    INK_DEFAULTS,
    LATTICE_CONTROLS,
    LATTICE_DEFAULTS,
    LENTICULAR_CONTROLS,
    LENTICULAR_DEFAULTS,
    MENISCUS_CONTROLS,
    MENISCUS_DEFAULTS,
    NIMBUS_CONTROLS,
    NIMBUS_DEFAULTS,
    PALIMPSEST_CONTROLS,
    PALIMPSEST_DEFAULTS,
    PEEL_CONTROLS,
    PEEL_DEFAULTS,
    PHOSPHOR_CONTROLS,
    PHOSPHOR_DEFAULTS,
    PRISM_CONTROLS,
    PRISM_DEFAULTS,
    QUARTZ_CONTROLS,
    QUARTZ_DEFAULTS,
    QUIVER_CONTROLS,
    QUIVER_DEFAULTS,
    SONAR_CONTROLS,
    SONAR_DEFAULTS,
    TIDE_CONTROLS,
    TIDE_DEFAULTS,
    DRENCH_CONTROLS,
    DRENCH_DEFAULTS,
    ECLIPSE_CONTROLS,
    ECLIPSE_DEFAULTS,
    ELEMENTAL_CONTROLS,
    ELEMENTAL_DEFAULTS,
    FACET_CONTROLS,
    FACET_DEFAULTS,
    GAZE_CONTROLS,
    GAZE_DEFAULTS,
    KERN_CONTROLS,
    KERN_DEFAULTS,
    LOADERS_CONTROLS,
    LOADERS_DEFAULTS,
    LODESTONE_CONTROLS,
    LODESTONE_DEFAULTS,
    LOUVRE_CONTROLS,
    LOUVRE_DEFAULTS,
    MEADOW_CONTROLS,
    MEADOW_DEFAULTS,
    OVERPRINT_CONTROLS,
    OVERPRINT_DEFAULTS,
    PERSEID_CONTROLS,
    PERSEID_DEFAULTS,
    RASTER_CONTROLS,
    RASTER_DEFAULTS,
    RICOCHET_CONTROLS,
    RICOCHET_DEFAULTS,
    TESSERA_CONTROLS,
    TESSERA_DEFAULTS,
    UNDERTOW_CONTROLS,
    UNDERTOW_DEFAULTS,
    WAKE_CONTROLS,
    WAKE_DEFAULTS,
    VELLUM_CONTROLS,
    VELLUM_DEFAULTS,
    WASH_CONTROLS,
    WASH_DEFAULTS,
} from "@/playground/experimental/schemas"
import {
    GRID_TRAIL_CONTROLS,
    GRID_TRAIL_DEMO_DEFAULTS,
    GRID_TRAIL_PRESETS,
    GRID_TRAIL_PRESET_VALUES,
} from "@/playground/grid-trail/schema"
import {
    REEL_CONTROLS,
    REEL_DEFAULTS,
    REEL_PRESETS,
    REEL_PRESET_VALUES,
} from "@/playground/reel/schema"
import {
    SCROLL_STACK_CONTROLS,
    SCROLL_STACK_DEFAULTS,
    SCROLL_STACK_PRESETS,
    SCROLL_STACK_PRESET_VALUES,
} from "@/playground/scroll-stack/schema"
import {
    SPLIT_FLAP_CONTROLS,
    SPLIT_FLAP_DEFAULTS,
    SPLIT_FLAP_PRESETS,
    SPLIT_FLAP_PRESET_VALUES,
} from "@/playground/split-flap/schema"
import {
    STENCIL_CONTROLS,
    STENCIL_DEFAULTS,
    STENCIL_PRESETS,
    STENCIL_PRESET_VALUES,
} from "@/playground/stencil/schema"
import {
    TRAILING_CURSOR_CONTROLS,
    TRAILING_CURSOR_DEFAULTS,
    TRAILING_CURSOR_PRESETS,
    TRAILING_CURSOR_PRESET_VALUES,
} from "@/playground/trailing-cursor/schema"
import type { PanelPreset } from "@/playground/panel/types"

import type { DocCategory, DocEntry, DocPreset } from "./types"

/** Bridges the older `PanelPreset[]` + values map onto one preset shape. */
function presetsFrom(
    list: PanelPreset[],
    values: Record<string, Record<string, unknown>>,
): DocPreset[] {
    return list.map((preset) => ({
        id: preset.id,
        label: preset.label,
        hint: preset.hint,
        values: values[preset.id] ?? {},
    }))
}

export const REPOSITORY_URL = "https://github.com/VladyslavPilkevych/zerogravity-ui"

export const COMPONENTS: DocEntry[] = [
    {
        slug: "antigravity",
        name: "Antigravity",
        description: "A particle field that flows around the cursor and settles into formations.",
        category: "Pointer",
        status: "stable",
        dependencies: [],
        tags: ["particles", "canvas", "cursor", "hero"],
        defaults: ANTIGRAVITY_DEFAULTS as unknown as Record<string, unknown>,
        controls: ANTIGRAVITY_CONTROLS,
        presets: ANTIGRAVITY_PRESETS.map((preset) => ({
            id: preset.id,
            label: preset.label,
            hint: preset.hint,
            values: preset.options as Record<string, unknown>,
        })),
        extraProps: [
            {
                name: "onStats",
                type: "(stats: AntigravityStats) => void",
                default: "—",
                description: "Frame statistics: fps, particles drawn, batches, ms per frame.",
            },
            {
                name: "ref",
                type: "Ref<AntigravityHandle>",
                default: "—",
                description: "Imperative handle exposing burst() and colorBurst().",
            },
        ],
        preview: { minHeight: 520, bleed: true, wide: true },
    },
    {
        slug: "scroll-stack",
        name: "ScrollStack",
        description: "Full-height sections that slide over each other on scroll, and unstack back.",
        category: "Motion",
        status: "stable",
        dependencies: [],
        tags: ["scroll", "sticky", "cards", "sections"],
        defaults: SCROLL_STACK_DEFAULTS as unknown as Record<string, unknown>,
        controls: SCROLL_STACK_CONTROLS,
        presets: presetsFrom(
            SCROLL_STACK_PRESETS,
            SCROLL_STACK_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        omit: ["cards", "sizeMix"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "One element per card. Each becomes a sticky section.",
            },
            {
                name: "heights",
                type: "string[]",
                default: "—",
                description: "Per-card height override, in place of the shared height.",
            },
            {
                name: "onActiveChange",
                type: "(index: number) => void",
                default: "—",
                description: "Fires when the front-most card changes.",
            },
        ],
        children: "<article>Card one</article>",
        preview: {
            port: true,
            minHeight: 560,
            wide: true,
            note: "Scaled down to fit the frame: short cards and a small peek, so the whole deck is visible at once. On a page you would use full-height sections and no peek.",
        },
    },
    {
        slug: "aperture",
        name: "Aperture",
        description: "A full-bleed panel that closes into a framed card as you scroll, or opens.",
        category: "Motion",
        status: "stable",
        dependencies: [],
        tags: ["scroll", "clip-path", "frame", "reveal"],
        defaults: APERTURE_DEFAULTS as unknown as Record<string, unknown>,
        controls: APERTURE_CONTROLS,
        presets: presetsFrom(
            APERTURE_PRESETS,
            APERTURE_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "The panel content. It never rescales — only the window changes.",
            },
            {
                name: "onProgress",
                type: "(progress: number) => void",
                default: "—",
                description: "Scroll progress from 0 to 1.",
            },
        ],
        children: "<div>Panel content</div>",
        preview: {
            port: true,
            minHeight: 560,
            wide: true,
            note: "Scaled down to fit the frame, and set to open so the panel starts as a card and grows to full bleed. On a page the pane is the viewport and it reads page scroll.",
        },
    },
    {
        slug: "elemental",
        name: "Elemental",
        description: "An animated edge that wraps any content in electricity or fire.",
        category: "Media",
        status: "stable",
        dependencies: [],
        tags: ["border", "glow", "card", "effect", "decorative", "wrapper"],
        defaults: ELEMENTAL_DEFAULTS,
        controls: ELEMENTAL_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Whatever the edge wraps. It stays fully interactive.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Freeze the edge in its static state.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description: "Fall back to the static edge when the user asks for less motion.",
            },
        ],
        children: "<Card />",
        preview: { minHeight: 520 },
    },
    {
        slug: "louvre",
        name: "Louvre",
        description: "Sticky blinds whose slats rotate away to reveal the section behind them.",
        category: "Motion",
        status: "experimental",
        dependencies: [],
        tags: ["scroll", "blinds", "transition", "reveal"],
        defaults: LOUVRE_DEFAULTS,
        controls: LOUVRE_CONTROLS,
        extraProps: [
            {
                name: "front",
                type: "ReactNode",
                default: "—",
                description: "What the closed blinds show.",
            },
            {
                name: "back",
                type: "ReactNode",
                default: "—",
                description: "What is revealed once the slats open.",
            },
        ],
        preview: {
            port: true,
            minHeight: 560,
            wide: true,
            note: "Scaled down to fit the frame, so one full turn of the blinds is visible here. On a page the pane is the viewport and it reads page scroll.",
        },
    },
    {
        slug: "undertow",
        name: "Undertow",
        description:
            "Two images and one membrane: the pointer parts the surface and the picture beneath comes through.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["image", "reveal", "liquid", "pointer", "canvas"],
        defaults: UNDERTOW_DEFAULTS,
        controls: UNDERTOW_CONTROLS,
        extraProps: [
            {
                name: "frontSrc",
                type: "string",
                default: "—",
                description: "The image on top, the one the pointer parts.",
            },
            {
                name: "backSrc",
                type: "string",
                default: "—",
                description: "The image underneath, revealed where the surface is disturbed.",
            },
            {
                name: "alt",
                type: "string",
                default: "—",
                description: "Describes the pair; both images render into one canvas.",
            },
            {
                name: "objectPosition",
                type: "string",
                default: '"50% 50%"',
                description: "Where both images sit when the box crops them.",
            },
            {
                name: "aspect",
                type: "string",
                default: "—",
                description: "Locks the box to a ratio, for example `16 / 10`.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds the still, composed state instead of animating.",
            },
        ],
        preview: {
            minHeight: 460,
            note: "A tap works too, so the reveal is not lost on a touch screen.",
        },
    },
    {
        slug: "wake",
        name: "Wake",
        description: "A surface that answers the pointer: waves spread from wherever it moved.",
        category: "Pointer",
        status: "experimental",
        dependencies: [],
        tags: ["pointer", "liquid", "ripple", "surface", "canvas"],
        defaults: WAKE_DEFAULTS,
        controls: WAKE_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "The surface the waves run over. Stays interactive.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds the surface still.",
            },
        ],
        children: "<Section />",
        preview: { minHeight: 400, bleed: true },
    },
    {
        slug: "drench",
        name: "Drench",
        description: "A word that is already there, and rain that finds it.",
        category: "Typography",
        status: "experimental",
        dependencies: [],
        tags: ["type", "rain", "reveal", "canvas", "weather"],
        defaults: DRENCH_DEFAULTS,
        controls: DRENCH_CONTROLS,
        extraProps: [
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds the still, soaked state instead of animating.",
            },
        ],
        preview: {
            minHeight: 380,
            bleed: true,
            note: "The text stays real text: the canvas is decoration, and screen readers get the word.",
        },
    },
    {
        slug: "perseid",
        name: "Perseid",
        description: "A meteor shower with bright heads, tapered trails and real depth.",
        category: "Scenes",
        status: "experimental",
        dependencies: [],
        tags: ["meteor", "background", "canvas", "space", "ambient"],
        defaults: PERSEID_DEFAULTS,
        controls: PERSEID_CONTROLS,
        omit: ["paletteName"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Content laid over the sky.",
            },
            {
                name: "colors",
                type: "string[]",
                default: "PERSEID_COLORS",
                description: "The palette meteors are drawn from.",
            },
            {
                name: "seed",
                type: "number",
                default: "—",
                description: "Fixes the sky, so the same seed gives the same meteors every time.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds a still sky instead of animating.",
            },
        ],
        preview: { minHeight: 400, bleed: true },
    },
    {
        slug: "gaze",
        name: "Gaze",
        description: "A model whose eyes lead and whose head follows, wherever the pointer goes.",
        category: "Scenes",
        status: "experimental",
        dependencies: ["three"],
        tags: ["3d", "model", "pointer", "gltf", "webgl"],
        defaults: GAZE_DEFAULTS,
        controls: GAZE_CONTROLS,
        extraProps: [
            {
                name: "src",
                type: "string",
                default: "—",
                description: "A `.glb` or `.gltf` URL. Omit it for the built-in stand-in head.",
            },
            {
                name: "tracking",
                type: "{ head?, leftEye?, rightEye? }",
                default: "—",
                description: "Node names in your model. Missing ones are skipped.",
            },
            {
                name: "label",
                type: "string",
                default: '"A model that follows the pointer"',
                description: "Describes the model for anything that cannot see it.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds the neutral pose instead of following the pointer.",
            },
        ],
        preview: {
            minHeight: 420,
            note: "Three.js loads only when a Gaze mounts, so no other component pulls it in.",
        },
    },
    {
        slug: "eclipse",
        name: "Eclipse",
        description: "Each section pins, and the next one slides over it until nothing is left.",
        category: "Motion",
        status: "experimental",
        dependencies: [],
        tags: ["scroll", "sections", "cover", "sticky", "transition"],
        defaults: ECLIPSE_DEFAULTS,
        controls: ECLIPSE_CONTROLS,
        tag: "Eclipse",
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "One `EclipseSection` per panel. Order is the cover order.",
            },
            {
                name: "height",
                type: "string",
                default: '"100vh"',
                description: "How long each section stays pinned.",
            },
            {
                name: "scrollContainer",
                type: "RefObject<HTMLElement>",
                default: "—",
                description: "Drive it from a scrollable element instead of the page.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Drops the pinning entirely: sections simply follow one another.",
            },
            {
                name: "onActiveChange",
                type: "(index: number) => void",
                default: "—",
                description: "Called when the section in view changes, not on every frame.",
            },
        ],
        children: "<EclipseSection>One</EclipseSection>",
        preview: {
            port: true,
            minHeight: 560,
            wide: true,
            note: "Scaled to the frame so the whole takeover is visible here. On a page each section is a full viewport.",
        },
    },
    {
        slug: "prism",
        name: "Prism",
        description:
            "A slab of glass that leans with the pointer and splits the light at its edges.",
        category: "Pointer",
        status: "experimental",
        dependencies: [],
        tags: ["glass", "refraction", "card", "tilt", "wrapper"],
        defaults: PRISM_DEFAULTS,
        controls: PRISM_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Whatever sits inside the glass. Stays interactive.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Holds the slab flat.",
            },
        ],
        children: "<Card />",
        preview: { minHeight: 420 },
    },
    {
        slug: "gnomon",
        name: "Gnomon",
        description:
            "The pointer becomes a lamp, and everything inside casts a shadow away from it.",
        category: "Pointer",
        status: "experimental",
        dependencies: [],
        tags: ["shadow", "light", "depth", "wrapper", "css"],
        defaults: GNOMON_DEFAULTS,
        controls: GNOMON_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Each direct child casts its own shadow.",
            },
            {
                name: "disabled",
                type: "boolean",
                default: "false",
                description: "Pins the light where it started.",
            },
        ],
        children: "<Card />",
        preview: { minHeight: 380 },
    },
    {
        slug: "lattice",
        name: "Lattice",
        description:
            "A line mesh that bulges away from the pointer, and lets go where it stretches.",
        category: "Pointer",
        status: "experimental",
        dependencies: [],
        tags: ["mesh", "lines", "canvas", "field", "background"],
        defaults: LATTICE_DEFAULTS,
        controls: LATTICE_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Content laid over the mesh.",
            },
        ],
        preview: { minHeight: 420, bleed: true },
    },
    {
        slug: "chroma",
        name: "Chroma",
        description: "A drag trail whose colour channels lag behind each other at speed.",
        category: "Pointer",
        status: "experimental",
        dependencies: [],
        tags: ["trail", "chromatic", "pointer", "canvas", "rgb"],
        defaults: CHROMA_DEFAULTS,
        controls: CHROMA_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "The surface the trail is drawn over.",
            },
        ],
        preview: { minHeight: 400, bleed: true },
    },
    {
        slug: "sonar",
        name: "Sonar",
        description: "A dot field that a shockwave crosses whenever the surface is pressed.",
        category: "Pointer",
        status: "experimental",
        dependencies: [],
        tags: ["shockwave", "dots", "ripple", "canvas", "press"],
        defaults: SONAR_DEFAULTS,
        controls: SONAR_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Content laid over the field.",
            },
        ],
        preview: { minHeight: 400, bleed: true },
    },
    {
        slug: "concertina",
        name: "Concertina",
        tag: "Concertina",
        description:
            "Panels hinged alternately, folding flat as they reach the middle of the view.",
        category: "Motion",
        status: "experimental",
        dependencies: [],
        tags: ["scroll", "fold", "sections", "3d", "paper"],
        defaults: CONCERTINA_DEFAULTS,
        controls: CONCERTINA_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "One `ConcertinaPanel` per leaf.",
            },
            {
                name: "height",
                type: "string",
                default: '"62vh"',
                description: "How tall each leaf is.",
            },
            {
                name: "scrollContainer",
                type: "RefObject<HTMLElement>",
                default: "\u2014",
                description: "Drive it from a scrollable element instead of the page.",
            },
        ],
        children: "<ConcertinaPanel>Fold</ConcertinaPanel>",
        preview: { port: true, minHeight: 520, wide: true },
    },
    {
        slug: "peel",
        name: "Peel",
        description: "The top sheet lifts off the one underneath as the section scrolls past.",
        category: "Motion",
        status: "experimental",
        dependencies: [],
        tags: ["scroll", "reveal", "sheet", "sticky", "transition"],
        defaults: PEEL_DEFAULTS,
        controls: PEEL_CONTROLS,
        extraProps: [
            {
                name: "front",
                type: "ReactNode",
                default: "\u2014",
                description: "The sheet on top, the one that lifts away.",
            },
            {
                name: "back",
                type: "ReactNode",
                default: "\u2014",
                description: "What is underneath it.",
            },
            {
                name: "height",
                type: "string",
                default: '"100vh"',
                description: "How tall the pinned stage is.",
            },
            {
                name: "scrollContainer",
                type: "RefObject<HTMLElement>",
                default: "\u2014",
                description: "Drive it from a scrollable element instead of the page.",
            },
        ],
        preview: { port: true, minHeight: 520, wide: true },
    },
    {
        slug: "gantry",
        name: "Gantry",
        description: "A rail of cards that travels sideways while the page scrolls down.",
        category: "Motion",
        status: "experimental",
        dependencies: [],
        tags: ["scroll", "horizontal", "rail", "sticky", "gallery"],
        defaults: GANTRY_DEFAULTS,
        controls: GANTRY_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "One card per stop along the rail.",
            },
            {
                name: "height",
                type: "string",
                default: '"80vh"',
                description: "How tall the pinned stage is.",
            },
            {
                name: "label",
                type: "string",
                default: '"Horizontal gallery"',
                description: "Names the rail once reduced motion turns it into a scroller.",
            },
            {
                name: "onProgress",
                type: "(progress: number) => void",
                default: "\u2014",
                description: "Called with 0 to 1 as the rail travels.",
            },
        ],
        children: "<Card />",
        preview: { port: true, minHeight: 520, wide: true },
    },
    {
        slug: "tide",
        name: "Tide",
        description: "A liquid separator between two sections that never sits still.",
        category: "Motion",
        status: "experimental",
        dependencies: [],
        tags: ["divider", "wave", "svg", "separator", "ambient"],
        defaults: TIDE_DEFAULTS,
        controls: TIDE_CONTROLS,
        omit: ["layers"],
        extraProps: [
            {
                name: "layers",
                type: "1 | 2",
                default: "2",
                description: "A second, slower wave behind the first.",
            },
        ],
        preview: { minHeight: 340, bleed: true },
    },
    {
        slug: "palimpsest",
        name: "Palimpsest",
        description: "A word that comes apart into the drafts written underneath it.",
        category: "Typography",
        status: "experimental",
        dependencies: [],
        tags: ["type", "layers", "ghost", "decomposition", "hover"],
        defaults: PALIMPSEST_DEFAULTS,
        controls: PALIMPSEST_CONTROLS,
        extraProps: [
            {
                name: "as",
                type: '"span" | "h1" | "h2" | "h3" | "p"',
                default: '"span"',
                description: "The tag the real text is rendered as.",
            },
            {
                name: "colors",
                type: "string[]",
                default: "PALIMPSEST_COLORS",
                description: "The tints the ghost layers are drawn in.",
            },
        ],
        preview: { minHeight: 320 },
    },
    {
        slug: "quiver",
        name: "Quiver",
        description: "A crest that travels along a line of type, lifting letters as it passes.",
        category: "Typography",
        status: "experimental",
        dependencies: [],
        tags: ["type", "wave", "pointer", "letters", "css"],
        defaults: QUIVER_DEFAULTS,
        controls: QUIVER_CONTROLS,
        extraProps: [
            {
                name: "as",
                type: '"span" | "h1" | "h2" | "h3" | "p"',
                default: '"span"',
                description: "The tag the text is rendered as.",
            },
        ],
        preview: { minHeight: 300 },
    },
    {
        slug: "ink",
        name: "Ink",
        description: "A word that soaks into the paper instead of fading in.",
        category: "Typography",
        status: "experimental",
        dependencies: [],
        tags: ["type", "ink", "diffusion", "canvas", "paper"],
        defaults: INK_DEFAULTS,
        controls: INK_CONTROLS,
        preview: {
            minHeight: 360,
            bleed: true,
            note: "The word stays real text; the canvas is only how it is drawn.",
        },
    },
    {
        slug: "phosphor",
        name: "Phosphor",
        description: "Type burned into a tube: scanlines, bloom and three guns that disagree.",
        category: "Typography",
        status: "experimental",
        dependencies: [],
        tags: ["type", "crt", "scanline", "retro", "glow"],
        defaults: PHOSPHOR_DEFAULTS,
        controls: PHOSPHOR_CONTROLS,
        extraProps: [
            {
                name: "as",
                type: '"span" | "h1" | "h2" | "h3" | "p"',
                default: '"span"',
                description: "The tag the text is rendered as.",
            },
        ],
        preview: { minHeight: 300, bleed: true },
    },
    {
        slug: "lenticular",
        name: "Lenticular",
        description: "Two pictures interlaced under one lens, swapping as you move across it.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["image", "lens", "print", "pointer", "mask"],
        defaults: LENTICULAR_DEFAULTS,
        controls: LENTICULAR_CONTROLS,
        extraProps: [
            {
                name: "frontSrc",
                type: "string",
                default: "\u2014",
                description: "The image seen from the left.",
            },
            {
                name: "backSrc",
                type: "string",
                default: "\u2014",
                description: "The image seen from the right.",
            },
            {
                name: "alt",
                type: "string",
                default: "\u2014",
                description: "Describes the pair; one card, one description.",
            },
        ],
        preview: { minHeight: 460 },
    },
    {
        slug: "anaglyph",
        name: "Anaglyph",
        description: "A picture split into two eyes that converge wherever the pointer rests.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["image", "3d", "chromatic", "depth", "pointer"],
        defaults: ANAGLYPH_DEFAULTS,
        controls: ANAGLYPH_CONTROLS,
        extraProps: [
            {
                name: "src",
                type: "string",
                default: "\u2014",
                description: "Any image URL or local asset.",
            },
            {
                name: "alt",
                type: "string",
                default: "\u2014",
                description: "Describes the picture once, on the plate underneath.",
            },
        ],
        preview: { minHeight: 460 },
    },
    {
        slug: "contact",
        name: "Contact",
        description: "A contact sheet you scrub through with the pointer or the arrow keys.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["image", "sequence", "scrub", "slider", "gallery"],
        defaults: CONTACT_DEFAULTS,
        controls: CONTACT_CONTROLS,
        extraProps: [
            {
                name: "frames",
                type: "string[]",
                default: "\u2014",
                description: "The sequence, in order.",
            },
            {
                name: "labels",
                type: "string[]",
                default: "\u2014",
                description: "A label per frame, read out by the slider.",
            },
            {
                name: "onFrameChange",
                type: "(index: number) => void",
                default: "\u2014",
                description: "Called when the frame changes, not on every move.",
            },
        ],
        preview: { minHeight: 480 },
    },
    {
        slug: "emulsion",
        name: "Emulsion",
        description: "A photographic treatment: halation, grain, a light leak and lifted shadows.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["image", "film", "grain", "halation", "css"],
        defaults: EMULSION_DEFAULTS,
        controls: EMULSION_CONTROLS,
        extraProps: [
            {
                name: "src",
                type: "string",
                default: "\u2014",
                description: "Any image URL or local asset.",
            },
            {
                name: "alt",
                type: "string",
                default: "\u2014",
                description: "Empty string if the image is decorative.",
            },
            {
                name: "aspect",
                type: "string",
                default: '"3 / 2"',
                description: "Locks the frame to a ratio.",
            },
        ],
        preview: { minHeight: 460 },
    },
    {
        slug: "quartz",
        name: "Quartz",
        description: "Film grain over anything, from one tile painted once and repeated by CSS.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["grain", "noise", "texture", "wrapper", "overlay"],
        defaults: QUARTZ_DEFAULTS,
        controls: QUARTZ_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Whatever the grain sits over.",
            },
        ],
        children: "<Hero />",
        preview: { minHeight: 380, bleed: true },
    },
    {
        slug: "nimbus",
        name: "Nimbus",
        description: "Slow coloured fog for a section background, drawn small and stretched up.",
        category: "Scenes",
        status: "experimental",
        dependencies: [],
        tags: ["fog", "background", "ambient", "canvas", "gradient"],
        defaults: NIMBUS_DEFAULTS,
        controls: NIMBUS_CONTROLS,
        omit: ["paletteName"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Content laid over the fog.",
            },
            {
                name: "colors",
                type: "string[]",
                default: "NIMBUS_COLORS",
                description: "The clouds it is built from.",
            },
        ],
        preview: { minHeight: 420, bleed: true },
    },
    {
        slug: "meniscus",
        name: "Meniscus",
        description: "A vessel that fills with liquid, and keeps sloshing while it waits.",
        category: "Feedback",
        status: "experimental",
        dependencies: [],
        tags: ["loader", "progress", "liquid", "svg", "feedback"],
        defaults: MENISCUS_DEFAULTS,
        controls: MENISCUS_CONTROLS,
        extraProps: [
            {
                name: "label",
                type: "string",
                default: '"Loading"',
                description: "What the progress bar announces.",
            },
            {
                name: "children",
                type: "ReactNode",
                default: "\u2014",
                description: "Replaces the number inside the vessel.",
            },
        ],
        preview: { minHeight: 340 },
    },
    {
        slug: "reel",
        name: "Reel",
        description: "A roulette-style carousel you can drag, flick, scroll sideways or step.",
        category: "Media",
        status: "stable",
        dependencies: [],
        tags: ["carousel", "slider", "coverflow", "drag"],
        defaults: REEL_DEFAULTS as unknown as Record<string, unknown>,
        controls: REEL_CONTROLS,
        presets: presetsFrom(
            REEL_PRESETS,
            REEL_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        omit: ["items"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "One element per slide.",
            },
            {
                name: "index",
                type: "number",
                default: "—",
                description: "Controlled index of the centred slide.",
            },
            {
                name: "onIndexChange",
                type: "(index: number) => void",
                default: "—",
                description: "Fires when a different slide reaches the centre.",
            },
            {
                name: "label",
                type: "string",
                default: '"Carousel"',
                description: "Accessible name for the carousel region.",
            },
        ],
        children: "<article>Slide one</article>",
        preview: { minHeight: 520, wide: true },
    },
    {
        slug: "raster",
        name: "Raster",
        description: "One picture through four stylised abstractions: blur, glass, glyph, pixel.",
        category: "Media",
        status: "experimental",
        dependencies: [],
        tags: ["image", "canvas", "pixel", "ascii", "filter"],
        defaults: RASTER_DEFAULTS,
        controls: RASTER_CONTROLS,
        extraProps: [
            {
                name: "src",
                type: "string",
                default: "—",
                description: "Image URL or imported asset.",
            },
            {
                name: "alt",
                type: "string",
                default: "—",
                description: "Alternative text. Empty string if the image is decorative.",
            },
            {
                name: "aspectRatio",
                type: "string",
                default: '"16 / 9"',
                description: "CSS aspect ratio for the frame.",
            },
        ],
        preview: { minHeight: 460 },
    },
    {
        slug: "stencil",
        name: "Stencil",
        description: "Display type filled with stripes, checks, gradients, an image or video.",
        category: "Typography",
        status: "stable",
        dependencies: [],
        tags: ["type", "text", "pattern", "mask", "heading"],
        defaults: STENCIL_DEFAULTS as unknown as Record<string, unknown>,
        controls: STENCIL_CONTROLS,
        presets: presetsFrom(
            STENCIL_PRESETS,
            STENCIL_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        extraProps: [
            {
                name: "media",
                type: "string",
                default: "—",
                description: "Video URL used by the reveal hover mode.",
            },
        ],
        preview: { minHeight: 380 },
    },
    {
        slug: "split-flap",
        name: "SplitFlap",
        description:
            "An airport board that flips one character at a time: text, clock or countdown.",
        category: "Typography",
        status: "stable",
        dependencies: [],
        tags: ["board", "flip", "clock", "countdown", "text"],
        defaults: SPLIT_FLAP_DEFAULTS as unknown as Record<string, unknown>,
        controls: SPLIT_FLAP_CONTROLS,
        presets: presetsFrom(
            SPLIT_FLAP_PRESETS,
            SPLIT_FLAP_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        extraProps: [
            {
                name: "target",
                type: "Date | number",
                default: "—",
                description: "Deadline for countdown mode.",
            },
        ],
        preview: { minHeight: 340 },
    },
    {
        slug: "kern",
        name: "Kern",
        description: "Glyphs that open up, lift and gain weight as the pointer passes them.",
        category: "Typography",
        status: "stable",
        dependencies: [],
        tags: ["type", "text", "pointer", "variable font"],
        defaults: KERN_DEFAULTS,
        controls: KERN_CONTROLS,
        preview: { minHeight: 340 },
    },
    {
        slug: "overprint",
        name: "Overprint",
        description:
            "Colour separations that misregister on scroll and converge back into register.",
        category: "Typography",
        status: "stable",
        dependencies: [],
        tags: ["type", "text", "scroll", "print", "cmyk"],
        defaults: OVERPRINT_DEFAULTS,
        controls: OVERPRINT_CONTROLS,
        preview: {
            minHeight: 340,
            note: "Scrolling the page shifts the plates apart; they converge again when it stops.",
        },
    },
    {
        slug: "grid-trail",
        name: "GridTrail",
        description: "A pointer trail that lights cells on an invisible grid, then stops the loop.",
        category: "Pointer",
        status: "stable",
        dependencies: [],
        tags: ["cursor", "grid", "trail", "background"],
        defaults: GRID_TRAIL_DEMO_DEFAULTS as unknown as Record<string, unknown>,
        controls: GRID_TRAIL_CONTROLS,
        presets: presetsFrom(
            GRID_TRAIL_PRESETS,
            GRID_TRAIL_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        omit: ["scoped"],
        extraProps: [
            {
                name: "container",
                type: "RefObject<HTMLElement>",
                default: "—",
                description: "Scope the trail to one element instead of the viewport.",
            },
            {
                name: "zIndex",
                type: "number",
                default: "0",
                description: "Stacking level of the trail canvas.",
            },
        ],
        preview: { minHeight: 420, bleed: true, containFixed: true },
    },
    {
        slug: "trailing-cursor",
        name: "TrailingCursor",
        description: "A dot pinned to the pointer and a ring that lags, grows and recolours.",
        category: "Pointer",
        status: "stable",
        dependencies: [],
        tags: ["cursor", "pointer", "ring", "hover"],
        defaults: TRAILING_CURSOR_DEFAULTS as unknown as Record<string, unknown>,
        controls: TRAILING_CURSOR_CONTROLS,
        presets: presetsFrom(
            TRAILING_CURSOR_PRESETS,
            TRAILING_CURSOR_PRESET_VALUES as Record<string, Record<string, unknown>>,
        ),
        preview: { minHeight: 460, bleed: true, containFixed: true },
    },
    {
        slug: "lodestone",
        name: "Lodestone",
        description: "Magnetic buttons that lean toward the pointer but never overlap each other.",
        category: "Pointer",
        status: "stable",
        dependencies: [],
        tags: ["button", "magnet", "cursor", "cta"],
        defaults: LODESTONE_DEFAULTS,
        controls: LODESTONE_CONTROLS,
        omit: ["buttons", "spacing"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Button label.",
            },
        ],
        children: "Get started",
        preview: { minHeight: 340 },
    },
    {
        slug: "vellum",
        name: "Vellum",
        description: "A sheet that leans toward the pointer, with an optional dent and sheen.",
        category: "Pointer",
        status: "stable",
        dependencies: [],
        tags: ["tilt", "card", "3d", "hover"],
        defaults: VELLUM_DEFAULTS,
        controls: VELLUM_CONTROLS,
        omit: ["highlight", "dent", "sheen", "sheenColor"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Whatever sits on the sheet.",
            },
            {
                name: "highlight",
                type: "VellumHighlight | false",
                default: "false",
                description: "Dent and sheen settings, or false to switch both off.",
            },
        ],
        children: "<div>Card</div>",
        preview: { minHeight: 400 },
    },
    {
        slug: "diorama",
        name: "Diorama",
        description:
            "Depth layers that part as the pointer moves, letting you see past the foreground.",
        category: "Pointer",
        status: "stable",
        dependencies: [],
        tags: ["parallax", "depth", "layers", "pointer"],
        defaults: DIORAMA_DEFAULTS,
        controls: DIORAMA_CONTROLS,
        extraProps: [
            {
                name: "background",
                type: "ReactNode",
                default: "—",
                description: "The deepest layer, never blurred.",
            },
            {
                name: "planes",
                type: "DioramaPlane[]",
                default: "[]",
                description: "Foreground layers, each with its own content and depth.",
            },
        ],
        preview: { minHeight: 420 },
    },
    {
        slug: "facet",
        name: "Facet",
        description:
            "A faceted surface whose colour migrates across the slats instead of switching.",
        category: "Pointer",
        status: "experimental",
        dependencies: [],
        tags: ["background", "hero", "gradient", "ambient"],
        defaults: FACET_DEFAULTS,
        controls: FACET_CONTROLS,
        omit: ["paletteName"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Content laid over the surface.",
            },
            {
                name: "palette",
                type: "string[]",
                default: "—",
                description: "Colours the ambient flow moves between.",
            },
        ],
        children: "<div>Hero copy</div>",
        preview: { minHeight: 460, bleed: true },
    },
    {
        slug: "wash",
        name: "Wash",
        description: "A new colour that spreads outward from wherever the surface was touched.",
        category: "Pointer",
        status: "experimental",
        dependencies: [],
        tags: ["background", "ripple", "colour", "click"],
        defaults: WASH_DEFAULTS,
        controls: WASH_CONTROLS,
        omit: ["paletteName"],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Content laid over the wash. Stays interactive.",
            },
            {
                name: "colors",
                type: "string[]",
                default: "—",
                description: "The cycle of colours to bloom through.",
            },
        ],
        children: "<div>Hero copy</div>",
        preview: { minHeight: 460, bleed: true },
    },
    {
        slug: "meadow",
        name: "Meadow",
        description:
            "A living pastel hero scene that drifts, bobs and flutters around your content.",
        category: "Scenes",
        status: "stable",
        dependencies: [],
        tags: ["hero", "illustration", "scene", "svg", "playful"],
        defaults: MEADOW_DEFAULTS,
        controls: MEADOW_CONTROLS,
        omit: [
            "sun",
            "clouds",
            "hills",
            "flowers",
            "balloon",
            "butterflies",
            "birds",
            "mascots",
            "stars",
            "comets",
            "planets",
            "rockets",
            "ufos",
        ],
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Content centred inside the scene.",
            },
            {
                name: "scene",
                type: "MeadowScene",
                default: "{}",
                description: "Per-element switches, for example { birds: false, flowers: false }.",
            },
        ],
        children: "<div>Hero copy</div>",
        preview: { minHeight: 520, bleed: true, wide: true },
    },
    {
        slug: "tessera",
        name: "Tessera",
        description:
            "A tiled route transition: tiles cover the viewport, the route swaps, they retreat.",
        category: "Scenes",
        status: "stable",
        tag: "TesseraProvider",
        dependencies: [],
        tags: ["route", "transition", "page", "tiles", "navigation"],
        defaults: TESSERA_DEFAULTS,
        controls: TESSERA_CONTROLS,
        extraProps: [
            {
                name: "children",
                type: "ReactNode",
                default: "—",
                description: "Your app. Navigation runs through useTessera().",
            },
        ],
        children: "<App />",
        preview: {
            minHeight: 440,
            bleed: true,
            containFixed: true,
            note: "The overlay is position: fixed in real use. It is held inside this frame so the docs stay usable.",
        },
    },
    {
        slug: "ricochet",
        name: "Ricochet",
        description:
            "Short text built from destructible pixel blocks, with breakout or shooter play.",
        category: "Scenes",
        status: "stable",
        dependencies: [],
        tags: ["404", "game", "pixel", "canvas", "arcade"],
        defaults: RICOCHET_DEFAULTS,
        controls: RICOCHET_CONTROLS,
        extraProps: [
            {
                name: "onClear",
                type: "() => void",
                default: "—",
                description: "Fires once, when the last block is destroyed.",
            },
            {
                name: "interactive",
                type: "boolean",
                default: "true",
                description: "Pointer, keyboard and focus handling.",
            },
            {
                name: "respectReducedMotion",
                type: "boolean",
                default: "true",
                description: "Render the text standing still when the user asks for less motion.",
            },
        ],
        preview: { minHeight: 480 },
    },
    {
        slug: "loaders",
        name: "Pixel loaders",
        description:
            "Four retro-digital loading states: a heart, blocks, a bar and a full-screen pulse.",
        category: "Feedback",
        status: "experimental",
        tag: "PixelHeart",
        dependencies: [],
        tags: ["loading", "spinner", "pixel", "progress", "skeleton"],
        defaults: LOADERS_DEFAULTS,
        controls: LOADERS_CONTROLS,
        omit: ["heartVariant", "blocksVariant", "determinate", "value"],
        extraProps: [
            {
                name: "variant",
                type: '"pulse" | "blink"',
                default: '"pulse"',
                description: "PixelHeart animation style.",
            },
            {
                name: "value",
                type: "number",
                default: "—",
                description: "PixelBar progress from 0 to 1. Omit for an indeterminate bar.",
            },
            {
                name: "label",
                type: "string",
                default: '"Loading"',
                description: "Announced by screen readers while the loader is visible.",
            },
        ],
        preview: { scroll: true, minHeight: 520, wide: true },
    },
]

export const COMPONENT_COUNT = COMPONENTS.length

/** The light list the sidebar needs, so schemas stay out of the client bundle. */
export function sidebarIndex() {
    return COMPONENTS.map((entry) => ({
        slug: entry.slug,
        name: entry.name,
        description: entry.description,
        category: entry.category,
        status: entry.status,
        tags: entry.tags,
    }))
}

export function findComponent(slug: string): DocEntry | undefined {
    return COMPONENTS.find((entry) => entry.slug === slug)
}

export function groupByCategory(
    entries: DocEntry[],
): { category: DocCategory; items: DocEntry[] }[] {
    const groups: { category: DocCategory; items: DocEntry[] }[] = []

    for (const entry of entries) {
        const found = groups.find((group) => group.category === entry.category)
        if (found) found.items.push(entry)
        else groups.push({ category: entry.category, items: [entry] })
    }

    return groups
}
