import type { ControlGroup } from "../panel/types"

const FORMATION_SHAPES = [
    "ring",
    "disc",
    "star",
    "polygon",
    "heart",
    "spiral",
    "grid",
    "wave",
    "lissajous",
    "blackhole",
    "planet",
    "torus",
    "sunflower",
    "arms",
    "rays",
    "dna",
    "atom",
    "tree",
] as const

const PARTICLE_SHAPES = [
    "dot",
    "square",
    "diamond",
    "bar",
    "triangle",
    "ring",
    "cross",
    "star",
] as const

const WAVEFORMS = [
    "sine",
    "triangle",
    "sawtooth",
    "square",
    "heartbeat",
    "decay",
    "organic",
] as const

const PULSE_MODES = ["sync", "scatter", "radial", "angular"] as const
const COLOR_MODES = ["random", "radial", "angular", "linear", "depth"] as const
const ROTATION_MODES = ["none", "radial", "tangential", "velocity", "spin"] as const
const ORIGINS = ["center", "random"] as const
const BLEND_MODES = ["normal", "lighter"] as const
const POINTER_SOURCES = ["parent", "window"] as const
const REPEL_FALLOFFS = ["linear", "smooth", "sharp"] as const

export const ANTIGRAVITY_CONTROLS: ControlGroup[] = [
    {
        id: "formation",
        title: "Formation",
        hint: "shape of the cloud",
        open: true,
        controls: [
            { kind: "number", path: "count", label: "Particles", min: 50, max: 8000, step: 10 },
            { kind: "select", path: "formation.shape", label: "Shape", options: FORMATION_SHAPES },
            {
                kind: "number",
                path: "formation.radius",
                label: "Radius",
                min: 40,
                max: 1200,
                step: 5,
                unit: "px",
            },
            {
                kind: "number",
                path: "formation.innerRatio",
                label: "Inner hole",
                min: 0,
                max: 0.98,
                step: 0.01,
            },
            {
                kind: "number",
                path: "formation.sides",
                label: "Sides / spikes",
                min: 2,
                max: 16,
                step: 1,
            },
            {
                kind: "number",
                path: "formation.depth",
                label: "Spike depth",
                min: 0,
                max: 0.95,
                step: 0.01,
            },
            {
                kind: "number",
                path: "formation.turns",
                label: "Spiral turns",
                min: 0.25,
                max: 8,
                step: 0.25,
            },
            {
                kind: "number",
                path: "formation.jitter",
                label: "Jitter",
                min: 0,
                max: 1,
                step: 0.01,
            },
            {
                kind: "number",
                path: "formation.angle",
                label: "Rotation",
                min: -180,
                max: 180,
                step: 1,
                unit: "°",
            },
            {
                kind: "number",
                path: "formation.aspect",
                label: "X stretch",
                min: 0.2,
                max: 3,
                step: 0.05,
            },
            {
                kind: "number",
                path: "formation.spin",
                label: "Spin",
                min: -90,
                max: 90,
                step: 1,
                unit: "°/s",
            },
            {
                kind: "number",
                path: "formation.tilt",
                label: "Tilt (planet / torus)",
                min: -90,
                max: 90,
                step: 1,
                unit: "°",
            },
            { kind: "number", path: "seed", label: "Seed", min: 1, max: 9999, step: 1 },
        ],
    },
    {
        id: "deform",
        title: "Deform",
        hint: "living blob distortion",
        open: false,
        controls: [
            {
                kind: "number",
                path: "deform.amount",
                label: "Amount",
                min: 0,
                max: 200,
                step: 1,
                unit: "px",
            },
            {
                kind: "number",
                path: "deform.frequency",
                label: "Frequency",
                min: 0.5,
                max: 12,
                step: 0.5,
            },
            { kind: "number", path: "deform.layers", label: "Harmonics", min: 1, max: 4, step: 1 },
            { kind: "number", path: "deform.speed", label: "Speed", min: 0, max: 3, step: 0.05 },
        ],
    },
    {
        id: "particle",
        title: "Particle",
        hint: "shape of a single dot",
        open: true,
        controls: [
            { kind: "select", path: "particle.shape", label: "Shape", options: PARTICLE_SHAPES },
            {
                kind: "number",
                path: "particle.size",
                label: "Size",
                min: 0.3,
                max: 14,
                step: 0.1,
                unit: "px",
            },
            {
                kind: "number",
                path: "particle.sizeVariance",
                label: "Size variance",
                min: 0,
                max: 1,
                step: 0.01,
            },
            {
                kind: "number",
                path: "particle.depthScale",
                label: "Depth influence",
                min: 0,
                max: 1,
                step: 0.01,
            },
            {
                kind: "number",
                path: "particle.length",
                label: "Length (bar)",
                min: 0.5,
                max: 20,
                step: 0.1,
            },
            {
                kind: "number",
                path: "particle.thickness",
                label: "Thickness (bar / ring / cross)",
                min: 0.05,
                max: 1,
                step: 0.01,
            },
            {
                kind: "number",
                path: "particle.points",
                label: "Points (star)",
                min: 2,
                max: 12,
                step: 1,
            },
            {
                kind: "number",
                path: "particle.depth",
                label: "Spike depth (star)",
                min: 0,
                max: 0.95,
                step: 0.01,
            },
            {
                kind: "select",
                path: "particle.rotation",
                label: "Rotation bound to",
                options: ROTATION_MODES,
            },
            {
                kind: "number",
                path: "particle.spin",
                label: "Spin speed",
                min: -720,
                max: 720,
                step: 5,
                unit: "°/s",
            },
            {
                kind: "number",
                path: "particle.angle",
                label: "Base angle",
                min: -180,
                max: 180,
                step: 1,
                unit: "°",
            },
        ],
    },
    {
        id: "color",
        title: "Colour",
        hint: "palette and shimmer",
        open: true,
        controls: [
            { kind: "palette", path: "color.palette", label: "Palette" },
            { kind: "select", path: "color.mode", label: "Assignment", options: COLOR_MODES },
            {
                kind: "number",
                path: "color.cycle",
                label: "Palette scroll",
                min: 0,
                max: 1,
                step: 0.005,
                unit: "loops/s",
            },
            { kind: "number", path: "color.opacity", label: "Opacity", min: 0, max: 1, step: 0.01 },
            {
                kind: "number",
                path: "color.opacityDepth",
                label: "Depth influence",
                min: 0,
                max: 1,
                step: 0.01,
            },
        ],
    },
    {
        id: "pulse",
        title: "Pulse",
        hint: "per-particle heartbeat",
        open: true,
        controls: [
            { kind: "boolean", path: "pulse.enabled", label: "Enabled" },
            { kind: "select", path: "pulse.waveform", label: "Pulse shape", options: WAVEFORMS },
            { kind: "select", path: "pulse.mode", label: "Phase spread", options: PULSE_MODES },
            {
                kind: "number",
                path: "pulse.speed",
                label: "Speed",
                min: 0,
                max: 4,
                step: 0.01,
                unit: "Hz",
            },
            {
                kind: "number",
                path: "pulse.size",
                label: "Size amount",
                min: 0,
                max: 2,
                step: 0.01,
            },
            {
                kind: "number",
                path: "pulse.opacity",
                label: "Opacity amount",
                min: 0,
                max: 1,
                step: 0.01,
            },
            {
                kind: "number",
                path: "pulse.spread",
                label: "Spatial spread",
                min: 0,
                max: 6,
                step: 0.05,
            },
        ],
    },
    {
        id: "wave",
        title: "Wave",
        hint: "breathing wave from the centre",
        open: false,
        controls: [
            { kind: "boolean", path: "wave.enabled", label: "Enabled" },
            { kind: "select", path: "wave.waveform", label: "Wave shape", options: WAVEFORMS },
            {
                kind: "number",
                path: "wave.speed",
                label: "Speed",
                min: 0,
                max: 3,
                step: 0.01,
                unit: "Hz",
            },
            {
                kind: "number",
                path: "wave.wavelength",
                label: "Wavelength",
                min: 40,
                max: 2000,
                step: 10,
                unit: "px",
            },
            {
                kind: "number",
                path: "wave.displace",
                label: "Displacement",
                min: 0,
                max: 200,
                step: 1,
                unit: "px",
            },
            { kind: "number", path: "wave.opacity", label: "Opacity", min: 0, max: 1, step: 0.01 },
            { kind: "number", path: "wave.size", label: "Size", min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: "burst",
        title: "Bursts",
        hint: "random shockwaves",
        open: false,
        controls: [
            { kind: "boolean", path: "burst.enabled", label: "Enabled" },
            { kind: "select", path: "burst.origin", label: "Origin", options: ORIGINS },
            { kind: "select", path: "burst.waveform", label: "Front shape", options: WAVEFORMS },
            {
                kind: "number",
                path: "burst.minInterval",
                label: "Gap from",
                min: 0.2,
                max: 20,
                step: 0.1,
                unit: "s",
            },
            {
                kind: "number",
                path: "burst.maxInterval",
                label: "Gap to",
                min: 0.2,
                max: 30,
                step: 0.1,
                unit: "s",
            },
            {
                kind: "number",
                path: "burst.strength",
                label: "Strength",
                min: 0,
                max: 3,
                step: 0.05,
            },
            {
                kind: "number",
                path: "burst.speed",
                label: "Front speed",
                min: 50,
                max: 3000,
                step: 10,
                unit: "px/s",
            },
            {
                kind: "number",
                path: "burst.width",
                label: "Front width",
                min: 20,
                max: 1200,
                step: 10,
                unit: "px",
            },
        ],
    },
    {
        id: "colorWave",
        title: "Colour wave",
        hint: "recolouring wave rolling across",
        open: false,
        controls: [
            { kind: "boolean", path: "colorWave.enabled", label: "Enabled" },
            { kind: "select", path: "colorWave.origin", label: "Origin", options: ORIGINS },
            {
                kind: "number",
                path: "colorWave.minInterval",
                label: "Gap from",
                min: 0,
                max: 20,
                step: 0.5,
                unit: "s",
            },
            {
                kind: "number",
                path: "colorWave.maxInterval",
                label: "Gap to",
                min: 0,
                max: 30,
                step: 0.5,
                unit: "s",
            },
            {
                kind: "number",
                path: "colorWave.duration",
                label: "Duration",
                min: 1,
                max: 25,
                step: 0.5,
                unit: "s",
            },
            {
                kind: "number",
                path: "colorWave.speed",
                label: "Speed",
                min: 20,
                max: 2000,
                step: 10,
                unit: "px/s",
            },
            {
                kind: "number",
                path: "colorWave.width",
                label: "Width",
                min: 50,
                max: 2500,
                step: 25,
                unit: "px",
            },
            {
                kind: "number",
                path: "colorWave.strength",
                label: "Strength",
                min: 0,
                max: 1,
                step: 0.01,
            },
            {
                kind: "number",
                path: "colorWave.saturation",
                label: "Saturation",
                min: 0,
                max: 100,
                step: 1,
                unit: "%",
            },
            {
                kind: "number",
                path: "colorWave.lightness",
                label: "Lightness",
                min: 0,
                max: 100,
                step: 1,
                unit: "%",
            },
            { kind: "palette", path: "colorWave.palette", label: "Own colours (empty = random)" },
        ],
    },
    {
        id: "follow",
        title: "Cursor",
        hint: "follow, repel, idle drift",
        open: true,
        controls: [
            { kind: "boolean", path: "follow.enabled", label: "Follow the cursor" },
            {
                kind: "boolean",
                path: "follow.returnToCenter",
                label: "Recentre when the cursor leaves",
            },
            {
                kind: "select",
                path: "follow.source",
                label: "Pointer area",
                options: POINTER_SOURCES,
            },
            {
                kind: "number",
                path: "follow.smooth",
                label: "Centre smoothing",
                min: 0.001,
                max: 0.3,
                step: 0.001,
            },
            {
                kind: "number",
                path: "follow.lag",
                label: "Particle lag",
                min: 0.001,
                max: 0.3,
                step: 0.001,
            },
            {
                kind: "number",
                path: "follow.lagSpread",
                label: "Lag spread",
                min: 0,
                max: 0.2,
                step: 0.001,
            },
            {
                kind: "boolean",
                path: "repel.enabled",
                label: "Push particles away from the cursor",
            },
            {
                kind: "number",
                path: "repel.radius",
                label: "Repel radius",
                min: 40,
                max: 700,
                step: 10,
                unit: "px",
            },
            {
                kind: "number",
                path: "repel.strength",
                label: "Repel strength (negative attracts)",
                min: -300,
                max: 400,
                step: 5,
                unit: "px",
            },
            {
                kind: "select",
                path: "repel.falloff",
                label: "Repel falloff",
                options: REPEL_FALLOFFS,
            },
            {
                kind: "number",
                path: "repel.ease",
                label: "Repel snappiness",
                min: 0.01,
                max: 0.5,
                step: 0.01,
            },
            {
                kind: "number",
                path: "drift.amount",
                label: "Idle drift",
                min: 0,
                max: 120,
                step: 1,
                unit: "px",
            },
            {
                kind: "number",
                path: "drift.speed",
                label: "Drift speed",
                min: 0,
                max: 4,
                step: 0.05,
            },
        ],
    },
    {
        id: "render",
        title: "Glow and render",
        hint: "compositing, trails, quality",
        open: false,
        controls: [
            { kind: "boolean", path: "glow.enabled", label: "Cursor glow" },
            {
                kind: "number",
                path: "glow.radius",
                label: "Glow radius",
                min: 40,
                max: 1200,
                step: 10,
                unit: "px",
            },
            { kind: "color", path: "glow.color", label: "Glow colour" },
            {
                kind: "number",
                path: "glow.intensity",
                label: "Glow intensity",
                min: 0,
                max: 0.6,
                step: 0.005,
            },
            { kind: "select", path: "render.blend", label: "Blending", options: BLEND_MODES },
            { kind: "number", path: "render.trail", label: "Trail", min: 0, max: 0.98, step: 0.01 },
            { kind: "colorNullable", path: "render.background", label: "Canvas background" },
            {
                kind: "number",
                path: "render.fadeIn",
                label: "Fade in",
                min: 0,
                max: 6000,
                step: 100,
                unit: "ms",
            },
            { kind: "number", path: "render.dprCap", label: "Max DPR", min: 1, max: 3, step: 0.5 },
            {
                kind: "boolean",
                path: "render.respectReducedMotion",
                label: "Respect reduced motion",
            },
            { kind: "boolean", path: "paused", label: "Paused" },
        ],
    },
]
