/** Kept in step with the docs registry by src/docs/registry.test.ts. */
export const COMPONENT_SLUGS = [
    "antigravity",
    "scroll-stack",
    "aperture",
    "elemental",
    "louvre",
    "reel",
    "raster",
    "stencil",
    "split-flap",
    "kern",
    "overprint",
    "grid-trail",
    "trailing-cursor",
    "lodestone",
    "vellum",
    "diorama",
    "facet",
    "wash",
    "meadow",
    "tessera",
    "ricochet",
    "loaders",
] as const
