import type { AntigravityOptions } from "./types"

export interface AntigravityPreset {
    id: string
    label: string
    hint: string
    options: AntigravityOptions
}

export const ANTIGRAVITY_PRESETS: AntigravityPreset[] = [
    {
        id: "nebula",
        label: "Nebula",
        hint: "Blob ring, pastel dots, drifting colour waves",
        options: {},
    },
    {
        id: "neon",
        label: "Neon bars",
        hint: "Bars aligned to motion, additive blending, trails",
        options: {
            count: 1400,
            formation: { shape: "ring", radius: 520, innerRatio: 0.15 },
            deform: { amount: 26, frequency: 3, layers: 3, speed: 0.5 },
            particle: {
                shape: "bar",
                size: 2.2,
                length: 6,
                thickness: 0.3,
                rotation: "velocity",
                sizeVariance: 0.4,
            },
            color: {
                palette: ["#00e5ff", "#7c4dff", "#ff2d95", "#00ffa3"],
                mode: "angular",
                cycle: 0.05,
                opacity: 0.9,
            },
            pulse: { waveform: "triangle", mode: "radial", speed: 0.4, size: 0.5, opacity: 0.3, spread: 1.4 },
            wave: { displace: 40, speed: 0.3 },
            glow: { color: "#7c4dff", radius: 460, intensity: 0.14 },
            render: { blend: "lighter", trail: 0.35 },
        },
    },
    {
        id: "heartbeat",
        label: "Heartbeat",
        hint: "Heart formation pulsing on an ECG waveform",
        options: {
            count: 1200,
            formation: { shape: "heart", radius: 420, innerRatio: 0.55, jitter: 0.05 },
            deform: { amount: 6, frequency: 5, layers: 2, speed: 0.5 },
            particle: { shape: "dot", size: 2.4, depthScale: 0.5 },
            color: {
                palette: ["#ff4d6d", "#ff8fa3", "#ffd6e0", "#c9184a"],
                mode: "radial",
                opacity: 0.9,
            },
            pulse: { waveform: "heartbeat", mode: "sync", speed: 0.7, size: 0.55, opacity: 0.35 },
            wave: { displace: 14, speed: 0.7, wavelength: 700 },
            burst: {
                enabled: true,
                origin: "center",
                waveform: "heartbeat",
                minInterval: 1.5,
                maxInterval: 4,
                strength: 0.5,
                speed: 900,
                width: 260,
            },
            colorWave: { enabled: false },
            glow: { color: "#ff4d6d", intensity: 0.12, radius: 340 },
        },
    },
    {
        id: "matrix",
        label: "Matrix grid",
        hint: "Grid, strobe pulse, scrolling green palette",
        options: {
            count: 2500,
            formation: { shape: "grid", radius: 520, jitter: 0.08 },
            deform: { amount: 0 },
            particle: { shape: "bar", size: 2, length: 3.4, thickness: 0.45, angle: 90 },
            color: {
                palette: ["#00ff9c", "#0aff0a", "#063d2a"],
                mode: "linear",
                cycle: 0.12,
                opacity: 0.8,
            },
            pulse: { waveform: "square", mode: "radial", speed: 0.5, size: 0.2, opacity: 0.7, spread: 2 },
            wave: { enabled: false },
            colorWave: {
                enabled: true,
                palette: ["#c8ffe4"],
                minInterval: 0.5,
                maxInterval: 2,
                duration: 5,
                speed: 420,
                width: 380,
            },
            follow: { lag: 0.05, lagSpread: 0.05 },
            drift: { amount: 4, speed: 0.6 },
            glow: { color: "#00ff9c", intensity: 0.1, radius: 300 },
            render: { trail: 0.2 },
        },
    },
    {
        id: "starfield",
        label: "Starfield",
        hint: "Spinning stars with random shockwaves",
        options: {
            count: 700,
            formation: { shape: "disc", radius: 600 },
            deform: { amount: 0 },
            particle: {
                shape: "star",
                size: 3.4,
                points: 4,
                depth: 0.72,
                sizeVariance: 0.8,
                rotation: "spin",
                spin: 40,
            },
            color: {
                palette: ["#fff8e7", "#ffd9a0", "#a0c4ff", "#ffffff"],
                mode: "random",
                opacity: 0.95,
                opacityDepth: 0.7,
            },
            pulse: { waveform: "organic", mode: "scatter", speed: 0.35, size: 0.45, opacity: 0.5 },
            wave: { enabled: false },
            burst: {
                enabled: true,
                origin: "random",
                waveform: "decay",
                minInterval: 2,
                maxInterval: 6,
                strength: 1.2,
                speed: 1100,
                width: 420,
            },
            follow: { lag: 0.008, lagSpread: 0.012 },
            glow: { radius: 520, intensity: 0.06, color: "#a0c4ff" },
            render: { blend: "lighter" },
        },
    },
    {
        id: "galaxy",
        label: "Spiral galaxy",
        hint: "Self-rotating spiral, 3000 particles",
        options: {
            count: 3000,
            formation: {
                shape: "arms",
                sides: 2,
                radius: 560,
                innerRatio: 0.04,
                turns: 1.7,
                jitter: 0.1,
                spin: 8,
            },
            deform: { amount: 10, frequency: 2, layers: 2, speed: 0.2 },
            particle: { shape: "dot", size: 1.9, sizeVariance: 0.6, depthScale: 0.6 },
            color: {
                palette: ["#fff3c4", "#ffb570", "#c77dff", "#5390d9", "#2d1b69"],
                mode: "radial",
                cycle: 0.02,
                opacity: 0.85,
            },
            pulse: { mode: "scatter", speed: 0.2, size: 0.25 },
            wave: { displace: 10, speed: 0.15, wavelength: 900, opacity: 0.2 },
            colorWave: { minInterval: 2, maxInterval: 5 },
            follow: { lag: 0.01, lagSpread: 0.02 },
            glow: { radius: 380, intensity: 0.1, color: "#ffb570" },
            render: { blend: "lighter" },
        },
    },
    {
        id: "ripples",
        label: "Ripples",
        hint: "Hexagon of rings with constant shockwaves",
        options: {
            count: 1600,
            formation: { shape: "polygon", sides: 6, radius: 540, innerRatio: 0.2, spin: 4 },
            deform: { amount: 8, frequency: 4, layers: 2, speed: 0.3 },
            particle: { shape: "ring", size: 3.2, thickness: 0.45, sizeVariance: 0.4 },
            color: {
                palette: ["#7ee8fa", "#eec0c6", "#80ffdb"],
                mode: "angular",
                cycle: 0.08,
                opacity: 0.7,
            },
            pulse: { waveform: "sine", mode: "radial", speed: 0.25, size: 0.4, opacity: 0.3, spread: 1.6 },
            wave: { displace: 18, speed: 0.2 },
            burst: {
                enabled: true,
                origin: "center",
                waveform: "sine",
                minInterval: 1,
                maxInterval: 3,
                strength: 1,
                speed: 800,
                width: 300,
            },
            glow: { color: "#7ee8fa", intensity: 0.09 },
        },
    },
    {
        id: "blackhole",
        label: "Black hole",
        hint: "Accretion disc, dense at the event horizon",
        options: {
            count: 3200,
            formation: {
                shape: "blackhole",
                radius: 560,
                innerRatio: 0.2,
                aspect: 2.5,
                angle: -12,
                spin: 34,
            },
            deform: { amount: 6, frequency: 2, layers: 2, speed: 0.3 },
            particle: { shape: "dot", size: 1.7, sizeVariance: 0.7, depthScale: 0.5 },
            color: {
                palette: ["#fff3d6", "#ffb14a", "#ff5c1a", "#8c1d00", "#2b0700"],
                mode: "radial",
                opacity: 0.9,
            },
            pulse: { waveform: "organic", mode: "radial", speed: 0.5, size: 0.35, opacity: 0.4, spread: 2.2 },
            wave: { displace: 8, speed: 0.4, wavelength: 320, opacity: 0.25 },
            colorWave: { enabled: false },
            follow: { lag: 0.02, lagSpread: 0.03 },
            drift: { amount: 6, speed: 1.4 },
            glow: { color: "#ff7a1a", intensity: 0.16, radius: 420 },
            render: { blend: "lighter", trail: 0.42 },
        },
    },
    {
        id: "planet",
        label: "Planet",
        hint: "A real 3-D sphere of dots spinning on its axis",
        options: {
            count: 4000,
            formation: { shape: "planet", radius: 340, spin: 14, tilt: 22 },
            deform: { amount: 0 },
            particle: { shape: "dot", size: 2.1, sizeVariance: 0.25, depthScale: 0.55 },
            color: {
                palette: ["#7dd3fc", "#2563eb", "#1e3a8a", "#082f49"],
                mode: "depth",
                opacity: 0.95,
                opacityDepth: 0.8,
            },
            pulse: { mode: "scatter", speed: 0.2, size: 0.12 },
            wave: { enabled: false },
            colorWave: { minInterval: 3, maxInterval: 7, speed: 160, width: 500 },
            follow: { lag: 0.02, lagSpread: 0.02 },
            drift: { amount: 3, speed: 0.6 },
            glow: { color: "#38bdf8", intensity: 0.1, radius: 420 },
        },
    },
    {
        id: "rings",
        label: "Ring world",
        hint: "Tilted 3-D torus turning in place",
        options: {
            count: 3000,
            formation: { shape: "torus", radius: 460, innerRatio: 0.16, spin: 16, tilt: 68 },
            deform: { amount: 0 },
            particle: { shape: "dot", size: 1.9, sizeVariance: 0.5, depthScale: 0.6 },
            color: {
                palette: ["#fde68a", "#fbbf24", "#b45309", "#78350f"],
                mode: "radial",
                cycle: 0.03,
                opacity: 0.85,
                opacityDepth: 0.7,
            },
            pulse: { mode: "scatter", speed: 0.3, size: 0.2 },
            wave: { enabled: false },
            colorWave: { enabled: false },
            glow: { color: "#fbbf24", intensity: 0.09, radius: 380 },
            render: { blend: "lighter" },
        },
    },
    {
        id: "sunflower",
        label: "Sunflower",
        hint: "Phyllotaxis spiral, one dot per seed",
        options: {
            count: 2600,
            formation: { shape: "sunflower", radius: 520, innerRatio: 0.05, spin: 3 },
            deform: { amount: 0 },
            particle: { shape: "diamond", size: 2.6, sizeVariance: 0.3, rotation: "radial" },
            color: {
                palette: ["#fff7cd", "#ffd166", "#f4801f", "#7b3f00"],
                mode: "radial",
                opacity: 0.9,
            },
            pulse: { waveform: "sine", mode: "radial", speed: 0.22, size: 0.3, opacity: 0.25, spread: 1.8 },
            wave: { displace: 6, speed: 0.2, wavelength: 700 },
            colorWave: { minInterval: 2, maxInterval: 6, width: 700 },
            glow: { color: "#ffd166", intensity: 0.08 },
        },
    },
    {
        id: "nova",
        label: "Nova",
        hint: "Radial spokes firing shockwaves",
        options: {
            count: 2400,
            formation: { shape: "rays", sides: 9, radius: 600, innerRatio: 0.12, spin: -6 },
            deform: { amount: 4, frequency: 3, layers: 1, speed: 0.4 },
            particle: { shape: "bar", size: 2, length: 7, thickness: 0.22, rotation: "radial" },
            color: { palette: ["#ffffff", "#a5f3fc", "#6366f1"], mode: "radial", opacity: 0.8 },
            pulse: { waveform: "decay", mode: "radial", speed: 0.6, size: 0.5, opacity: 0.5, spread: 2 },
            wave: { displace: 30, speed: 0.5, wavelength: 420 },
            burst: {
                enabled: true,
                origin: "center",
                waveform: "decay",
                minInterval: 1.2,
                maxInterval: 3,
                strength: 1.1,
                speed: 1200,
                width: 380,
            },
            glow: { color: "#6366f1", intensity: 0.12 },
            render: { blend: "lighter", trail: 0.25 },
        },
    },
    {
        id: "repel",
        label: "Repel field",
        hint: "Static grid that scatters away from the cursor",
        options: {
            count: 2600,
            formation: { shape: "grid", radius: 560, jitter: 0.04 },
            deform: { amount: 0 },
            particle: { shape: "dot", size: 2.4, sizeVariance: 0.3, depthScale: 0.35 },
            color: {
                palette: ["#dbe7ff", "#8ab4ff", "#3b5bdb"],
                mode: "linear",
                opacity: 0.8,
            },
            pulse: { mode: "scatter", speed: 0.18, size: 0.15 },
            wave: { enabled: false },
            colorWave: { enabled: false },
            follow: { enabled: false },
            repel: { enabled: true, radius: 260, strength: 130, falloff: "smooth", ease: 0.18 },
            drift: { amount: 4, speed: 0.5 },
            glow: { radius: 300, intensity: 0.07, color: "#8ab4ff" },
        },
    },
    {
        id: "minimal",
        label: "Minimal",
        hint: "Thin white ring, 320 dots",
        options: {
            count: 320,
            formation: { shape: "ring", radius: 460, innerRatio: 0.75 },
            deform: { amount: 18, frequency: 3, layers: 3, speed: 0.25 },
            particle: { shape: "dot", size: 1.8, depthScale: 0.3 },
            color: { palette: ["#ffffff"], mode: "random", opacity: 0.55, opacityDepth: 0.4 },
            pulse: { size: 0.2, speed: 0.2 },
            wave: { displace: 12, opacity: 0.1 },
            colorWave: { enabled: false },
            glow: { enabled: false },
        },
    },
]

export function getAntigravityPreset(id: string): AntigravityPreset | undefined {
    return ANTIGRAVITY_PRESETS.find((preset) => preset.id === id)
}
